package com.tuyou.tuyouerp.dao;

import com.xdjk.model.erp.Agents;
import com.xdjk.model.erp.AgentsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface AgentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agents
     *
     * @mbg.generated
     */
    long countByExample(AgentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agents
     *
     * @mbg.generated
     */
    int deleteByExample(AgentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agents
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer agentsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agents
     *
     * @mbg.generated
     */
    int insert(Agents record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agents
     *
     * @mbg.generated
     */
    int insertSelective(Agents record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agents
     *
     * @mbg.generated
     */
    List<Agents> selectByExampleWithRowbounds(AgentsExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agents
     *
     * @mbg.generated
     */
    List<Agents> selectByExample(AgentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agents
     *
     * @mbg.generated
     */
    Agents selectByPrimaryKey(Integer agentsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agents
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Agents record, @Param("example") AgentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agents
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Agents record, @Param("example") AgentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agents
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Agents record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agents
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Agents record);
}