package com.tuyou.tuyouerp.dao;

import com.xdjk.model.erp.CustomPay;
import com.xdjk.model.erp.CustomPayExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CustomPayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_pay
     *
     * @mbg.generated
     */
    long countByExample(CustomPayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_pay
     *
     * @mbg.generated
     */
    int deleteByExample(CustomPayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_pay
     *
     * @mbg.generated
     */
    int insert(CustomPay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_pay
     *
     * @mbg.generated
     */
    int insertSelective(CustomPay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_pay
     *
     * @mbg.generated
     */
    List<CustomPay> selectByExampleWithRowbounds(CustomPayExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_pay
     *
     * @mbg.generated
     */
    List<CustomPay> selectByExample(CustomPayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_pay
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CustomPay record, @Param("example") CustomPayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table custom_pay
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CustomPay record, @Param("example") CustomPayExample example);
}