package com.tuyou.tuyouerp.dao;

import com.xdjk.model.erp.EmployeeRole;
import com.xdjk.model.erp.EmployeeRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface EmployeeRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_role
     *
     * @mbg.generated
     */
    long countByExample(EmployeeRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_role
     *
     * @mbg.generated
     */
    int deleteByExample(EmployeeRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_role
     *
     * @mbg.generated
     */
    int insert(EmployeeRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_role
     *
     * @mbg.generated
     */
    int insertSelective(EmployeeRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_role
     *
     * @mbg.generated
     */
    List<EmployeeRole> selectByExampleWithRowbounds(EmployeeRoleExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_role
     *
     * @mbg.generated
     */
    List<EmployeeRole> selectByExample(EmployeeRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_role
     *
     * @mbg.generated
     */
    EmployeeRole selectByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EmployeeRole record, @Param("example") EmployeeRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EmployeeRole record, @Param("example") EmployeeRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EmployeeRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EmployeeRole record);
}