package com.tuyou.tuyouerp.dao;

import com.xdjk.model.erp.EnterpriseConfig;
import com.xdjk.model.erp.EnterpriseConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface EnterpriseConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_config
     *
     * @mbg.generated
     */
    long countByExample(EnterpriseConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_config
     *
     * @mbg.generated
     */
    int deleteByExample(EnterpriseConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_config
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer configId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_config
     *
     * @mbg.generated
     */
    int insert(EnterpriseConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_config
     *
     * @mbg.generated
     */
    int insertSelective(EnterpriseConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_config
     *
     * @mbg.generated
     */
    List<EnterpriseConfig> selectByExampleWithRowbounds(EnterpriseConfigExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_config
     *
     * @mbg.generated
     */
    List<EnterpriseConfig> selectByExample(EnterpriseConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_config
     *
     * @mbg.generated
     */
    EnterpriseConfig selectByPrimaryKey(Integer configId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_config
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EnterpriseConfig record, @Param("example") EnterpriseConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_config
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EnterpriseConfig record, @Param("example") EnterpriseConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EnterpriseConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EnterpriseConfig record);
}