package com.tuyou.tuyouerp.dao;

import com.xdjk.model.erp.LkEmployeeRole;
import com.xdjk.model.erp.LkEmployeeRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface LkEmployeeRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_employee_role
     *
     * @mbg.generated
     */
    long countByExample(LkEmployeeRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_employee_role
     *
     * @mbg.generated
     */
    int deleteByExample(LkEmployeeRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_employee_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer employeeRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_employee_role
     *
     * @mbg.generated
     */
    int insert(LkEmployeeRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_employee_role
     *
     * @mbg.generated
     */
    int insertSelective(LkEmployeeRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_employee_role
     *
     * @mbg.generated
     */
    List<LkEmployeeRole> selectByExampleWithRowbounds(LkEmployeeRoleExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_employee_role
     *
     * @mbg.generated
     */
    List<LkEmployeeRole> selectByExample(LkEmployeeRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_employee_role
     *
     * @mbg.generated
     */
    LkEmployeeRole selectByPrimaryKey(Integer employeeRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_employee_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LkEmployeeRole record, @Param("example") LkEmployeeRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_employee_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LkEmployeeRole record, @Param("example") LkEmployeeRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_employee_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LkEmployeeRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_employee_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LkEmployeeRole record);
}