package com.tuyou.tuyouerp.dao;

import com.xdjk.model.erp.LkStationAdmin;
import com.xdjk.model.erp.LkStationAdminExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface LkStationAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_station_admin
     *
     * @mbg.generated
     */
    long countByExample(LkStationAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_station_admin
     *
     * @mbg.generated
     */
    int deleteByExample(LkStationAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_station_admin
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer stationAdminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_station_admin
     *
     * @mbg.generated
     */
    int insert(LkStationAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_station_admin
     *
     * @mbg.generated
     */
    int insertSelective(LkStationAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_station_admin
     *
     * @mbg.generated
     */
    List<LkStationAdmin> selectByExampleWithRowbounds(LkStationAdminExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_station_admin
     *
     * @mbg.generated
     */
    List<LkStationAdmin> selectByExample(LkStationAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_station_admin
     *
     * @mbg.generated
     */
    LkStationAdmin selectByPrimaryKey(Integer stationAdminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_station_admin
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LkStationAdmin record, @Param("example") LkStationAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_station_admin
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LkStationAdmin record, @Param("example") LkStationAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_station_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LkStationAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_station_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LkStationAdmin record);
}