package com.tuyou.tuyouerp.dao;

import com.xdjk.model.erp.LkStationUser;
import com.xdjk.model.erp.LkStationUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface LkStationUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_station_user
     *
     * @mbg.generated
     */
    long countByExample(LkStationUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_station_user
     *
     * @mbg.generated
     */
    int deleteByExample(LkStationUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_station_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer stationUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_station_user
     *
     * @mbg.generated
     */
    int insert(LkStationUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_station_user
     *
     * @mbg.generated
     */
    int insertSelective(LkStationUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_station_user
     *
     * @mbg.generated
     */
    List<LkStationUser> selectByExampleWithRowbounds(LkStationUserExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_station_user
     *
     * @mbg.generated
     */
    List<LkStationUser> selectByExample(LkStationUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_station_user
     *
     * @mbg.generated
     */
    LkStationUser selectByPrimaryKey(Integer stationUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_station_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LkStationUser record, @Param("example") LkStationUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_station_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LkStationUser record, @Param("example") LkStationUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_station_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LkStationUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_station_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LkStationUser record);
}