package com.tuyou.tuyoucrm.dao;

import com.tuyou.tuyoucrm.vo.EmployeeMenu;
import com.tuyou.tuyoucrm.vo.EmployeeMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface EmployeeMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_menu
     *
     * @mbg.generated
     */
    long countByExample(EmployeeMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_menu
     *
     * @mbg.generated
     */
    int deleteByExample(EmployeeMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_menu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_menu
     *
     * @mbg.generated
     */
    int insert(EmployeeMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_menu
     *
     * @mbg.generated
     */
    int insertSelective(EmployeeMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_menu
     *
     * @mbg.generated
     */
    List<EmployeeMenu> selectByExampleWithRowbounds(EmployeeMenuExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_menu
     *
     * @mbg.generated
     */
    List<EmployeeMenu> selectByExample(EmployeeMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_menu
     *
     * @mbg.generated
     */
    EmployeeMenu selectByPrimaryKey(Integer menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_menu
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EmployeeMenu record, @Param("example") EmployeeMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_menu
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EmployeeMenu record, @Param("example") EmployeeMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EmployeeMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EmployeeMenu record);
}