package com.tuyou.tuyoucrm.dao;

import com.tuyou.tuyoucrm.vo.EnterpriseGradeConfig;
import com.tuyou.tuyoucrm.vo.EnterpriseGradeConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface EnterpriseGradeConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_grade_config
     *
     * @mbg.generated
     */
    long countByExample(EnterpriseGradeConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_grade_config
     *
     * @mbg.generated
     */
    int deleteByExample(EnterpriseGradeConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_grade_config
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer gradeConfigId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_grade_config
     *
     * @mbg.generated
     */
    int insert(EnterpriseGradeConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_grade_config
     *
     * @mbg.generated
     */
    int insertSelective(EnterpriseGradeConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_grade_config
     *
     * @mbg.generated
     */
    List<EnterpriseGradeConfig> selectByExampleWithRowbounds(EnterpriseGradeConfigExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_grade_config
     *
     * @mbg.generated
     */
    List<EnterpriseGradeConfig> selectByExample(EnterpriseGradeConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_grade_config
     *
     * @mbg.generated
     */
    EnterpriseGradeConfig selectByPrimaryKey(Integer gradeConfigId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_grade_config
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EnterpriseGradeConfig record, @Param("example") EnterpriseGradeConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_grade_config
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EnterpriseGradeConfig record, @Param("example") EnterpriseGradeConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_grade_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EnterpriseGradeConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_grade_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EnterpriseGradeConfig record);
}