package com.tuyou.tuyoucrm.dao;

import com.tuyou.tuyoucrm.vo.LkEmployeeRoleMenu;
import com.tuyou.tuyoucrm.vo.LkEmployeeRoleMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface LkEmployeeRoleMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_employee_role_menu
     *
     * @mbg.generated
     */
    long countByExample(LkEmployeeRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_employee_role_menu
     *
     * @mbg.generated
     */
    int deleteByExample(LkEmployeeRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_employee_role_menu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer roleMenuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_employee_role_menu
     *
     * @mbg.generated
     */
    int insert(LkEmployeeRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_employee_role_menu
     *
     * @mbg.generated
     */
    int insertSelective(LkEmployeeRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_employee_role_menu
     *
     * @mbg.generated
     */
    List<LkEmployeeRoleMenu> selectByExampleWithRowbounds(LkEmployeeRoleMenuExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_employee_role_menu
     *
     * @mbg.generated
     */
    List<LkEmployeeRoleMenu> selectByExample(LkEmployeeRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_employee_role_menu
     *
     * @mbg.generated
     */
    LkEmployeeRoleMenu selectByPrimaryKey(Integer roleMenuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_employee_role_menu
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LkEmployeeRoleMenu record, @Param("example") LkEmployeeRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_employee_role_menu
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LkEmployeeRoleMenu record, @Param("example") LkEmployeeRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_employee_role_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LkEmployeeRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_employee_role_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LkEmployeeRoleMenu record);
}