package com.tuyou.tuyoucrm.dao;

import com.tuyou.tuyoucrm.vo.LkUserStationAuth;
import com.tuyou.tuyoucrm.vo.LkUserStationAuthExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface LkUserStationAuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_user_station_auth
     *
     * @mbg.generated
     */
    long countByExample(LkUserStationAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_user_station_auth
     *
     * @mbg.generated
     */
    int deleteByExample(LkUserStationAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_user_station_auth
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer userOilId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_user_station_auth
     *
     * @mbg.generated
     */
    int insert(LkUserStationAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_user_station_auth
     *
     * @mbg.generated
     */
    int insertSelective(LkUserStationAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_user_station_auth
     *
     * @mbg.generated
     */
    List<LkUserStationAuth> selectByExampleWithRowbounds(LkUserStationAuthExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_user_station_auth
     *
     * @mbg.generated
     */
    List<LkUserStationAuth> selectByExample(LkUserStationAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_user_station_auth
     *
     * @mbg.generated
     */
    LkUserStationAuth selectByPrimaryKey(Integer userOilId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_user_station_auth
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LkUserStationAuth record, @Param("example") LkUserStationAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_user_station_auth
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LkUserStationAuth record, @Param("example") LkUserStationAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_user_station_auth
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LkUserStationAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_user_station_auth
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LkUserStationAuth record);
}