package com.tuyou.tuyoucrm.dao;

import com.tuyou.tuyoucrm.vo.RechargeGive;
import com.tuyou.tuyoucrm.vo.RechargeGiveExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface RechargeGiveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_give
     *
     * @mbg.generated
     */
    long countByExample(RechargeGiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_give
     *
     * @mbg.generated
     */
    int deleteByExample(RechargeGiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_give
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer rechargeGiveId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_give
     *
     * @mbg.generated
     */
    int insert(RechargeGive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_give
     *
     * @mbg.generated
     */
    int insertSelective(RechargeGive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_give
     *
     * @mbg.generated
     */
    List<RechargeGive> selectByExampleWithRowbounds(RechargeGiveExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_give
     *
     * @mbg.generated
     */
    List<RechargeGive> selectByExample(RechargeGiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_give
     *
     * @mbg.generated
     */
    RechargeGive selectByPrimaryKey(Integer rechargeGiveId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_give
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RechargeGive record, @Param("example") RechargeGiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_give
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RechargeGive record, @Param("example") RechargeGiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_give
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RechargeGive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_give
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RechargeGive record);
}