package com.tuyou.tuyoucrm.vo;

import java.io.Serializable;
import java.util.Date;

public class Agents implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agents.agents_id
     *
     * @mbg.generated
     */
    private Integer agentsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agents.company_name
     *
     * @mbg.generated
     */
    private String companyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agents.introduction
     *
     * @mbg.generated
     */
    private String introduction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agents.registered_no
     *
     * @mbg.generated
     */
    private String registeredNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agents.contact_name
     *
     * @mbg.generated
     */
    private String contactName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agents.contact_phone
     *
     * @mbg.generated
     */
    private String contactPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agents.hq_count
     *
     * @mbg.generated
     */
    private Integer hqCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agents.station_count
     *
     * @mbg.generated
     */
    private Integer stationCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agents.created_id
     *
     * @mbg.generated
     */
    private Integer createdId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agents.created_time
     *
     * @mbg.generated
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agents.created_name
     *
     * @mbg.generated
     */
    private String createdName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table agents
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agents.agents_id
     *
     * @return the value of agents.agents_id
     *
     * @mbg.generated
     */
    public Integer getAgentsId() {
        return agentsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agents.agents_id
     *
     * @param agentsId the value for agents.agents_id
     *
     * @mbg.generated
     */
    public void setAgentsId(Integer agentsId) {
        this.agentsId = agentsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agents.company_name
     *
     * @return the value of agents.company_name
     *
     * @mbg.generated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agents.company_name
     *
     * @param companyName the value for agents.company_name
     *
     * @mbg.generated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agents.introduction
     *
     * @return the value of agents.introduction
     *
     * @mbg.generated
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agents.introduction
     *
     * @param introduction the value for agents.introduction
     *
     * @mbg.generated
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agents.registered_no
     *
     * @return the value of agents.registered_no
     *
     * @mbg.generated
     */
    public String getRegisteredNo() {
        return registeredNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agents.registered_no
     *
     * @param registeredNo the value for agents.registered_no
     *
     * @mbg.generated
     */
    public void setRegisteredNo(String registeredNo) {
        this.registeredNo = registeredNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agents.contact_name
     *
     * @return the value of agents.contact_name
     *
     * @mbg.generated
     */
    public String getContactName() {
        return contactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agents.contact_name
     *
     * @param contactName the value for agents.contact_name
     *
     * @mbg.generated
     */
    public void setContactName(String contactName) {
        this.contactName = contactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agents.contact_phone
     *
     * @return the value of agents.contact_phone
     *
     * @mbg.generated
     */
    public String getContactPhone() {
        return contactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agents.contact_phone
     *
     * @param contactPhone the value for agents.contact_phone
     *
     * @mbg.generated
     */
    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agents.hq_count
     *
     * @return the value of agents.hq_count
     *
     * @mbg.generated
     */
    public Integer getHqCount() {
        return hqCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agents.hq_count
     *
     * @param hqCount the value for agents.hq_count
     *
     * @mbg.generated
     */
    public void setHqCount(Integer hqCount) {
        this.hqCount = hqCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agents.station_count
     *
     * @return the value of agents.station_count
     *
     * @mbg.generated
     */
    public Integer getStationCount() {
        return stationCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agents.station_count
     *
     * @param stationCount the value for agents.station_count
     *
     * @mbg.generated
     */
    public void setStationCount(Integer stationCount) {
        this.stationCount = stationCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agents.created_id
     *
     * @return the value of agents.created_id
     *
     * @mbg.generated
     */
    public Integer getCreatedId() {
        return createdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agents.created_id
     *
     * @param createdId the value for agents.created_id
     *
     * @mbg.generated
     */
    public void setCreatedId(Integer createdId) {
        this.createdId = createdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agents.created_time
     *
     * @return the value of agents.created_time
     *
     * @mbg.generated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agents.created_time
     *
     * @param createdTime the value for agents.created_time
     *
     * @mbg.generated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agents.created_name
     *
     * @return the value of agents.created_name
     *
     * @mbg.generated
     */
    public String getCreatedName() {
        return createdName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agents.created_name
     *
     * @param createdName the value for agents.created_name
     *
     * @mbg.generated
     */
    public void setCreatedName(String createdName) {
        this.createdName = createdName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agents
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", agentsId=").append(agentsId);
        sb.append(", companyName=").append(companyName);
        sb.append(", introduction=").append(introduction);
        sb.append(", registeredNo=").append(registeredNo);
        sb.append(", contactName=").append(contactName);
        sb.append(", contactPhone=").append(contactPhone);
        sb.append(", hqCount=").append(hqCount);
        sb.append(", stationCount=").append(stationCount);
        sb.append(", createdId=").append(createdId);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", createdName=").append(createdName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}