package com.tuyou.tuyoucrm.vo;

import java.io.Serializable;
import java.util.Date;

public class Enterprise extends com.spr.project.cbl.api.response.PageParameter implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.enterprise_id
     *
     * @mbg.generated
     */
    private Integer enterpriseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.enterprise_name
     *
     * @mbg.generated
     */
    private String enterpriseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.registered_name
     *
     * @mbg.generated
     */
    private String registeredName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.registered_no
     *
     * @mbg.generated
     */
    private String registeredNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.legal_person
     *
     * @mbg.generated
     */
    private String legalPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.contact_name
     *
     * @mbg.generated
     */
    private String contactName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.contact_phone
     *
     * @mbg.generated
     */
    private String contactPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.logo_url
     *
     * @mbg.generated
     */
    private String logoUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.province_id
     *
     * @mbg.generated
     */
    private String provinceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.province_name
     *
     * @mbg.generated
     */
    private String provinceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.city_id
     *
     * @mbg.generated
     */
    private String cityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.city_name
     *
     * @mbg.generated
     */
    private String cityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.total_short_name
     *
     * @mbg.generated
     */
    private String totalShortName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.agents_id
     *
     * @mbg.generated
     */
    private Integer agentsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.created_id
     *
     * @mbg.generated
     */
    private Integer createdId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.created_name
     *
     * @mbg.generated
     */
    private String createdName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.created_time
     *
     * @mbg.generated
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.Column_21
     *
     * @mbg.generated
     */
    private String column21;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.Column_22
     *
     * @mbg.generated
     */
    private String column22;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.Column_23
     *
     * @mbg.generated
     */
    private String column23;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.Column_24
     *
     * @mbg.generated
     */
    private Double column24;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.Column_25
     *
     * @mbg.generated
     */
    private Double column25;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.Column_26
     *
     * @mbg.generated
     */
    private Double column26;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.Column_27
     *
     * @mbg.generated
     */
    private Double column27;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.Column_28
     *
     * @mbg.generated
     */
    private Byte column28;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.Column_29
     *
     * @mbg.generated
     */
    private Byte column29;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.Column_30
     *
     * @mbg.generated
     */
    private Byte column30;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.Column_31
     *
     * @mbg.generated
     */
    private Byte column31;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.protect_amount
     *
     * @mbg.generated
     */
    private Double protectAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table enterprise
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.enterprise_id
     *
     * @return the value of enterprise.enterprise_id
     *
     * @mbg.generated
     */
    public Integer getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.enterprise_id
     *
     * @param enterpriseId the value for enterprise.enterprise_id
     *
     * @mbg.generated
     */
    public void setEnterpriseId(Integer enterpriseId) {
        this.enterpriseId = enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.enterprise_name
     *
     * @return the value of enterprise.enterprise_name
     *
     * @mbg.generated
     */
    public String getEnterpriseName() {
        return enterpriseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.enterprise_name
     *
     * @param enterpriseName the value for enterprise.enterprise_name
     *
     * @mbg.generated
     */
    public void setEnterpriseName(String enterpriseName) {
        this.enterpriseName = enterpriseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.registered_name
     *
     * @return the value of enterprise.registered_name
     *
     * @mbg.generated
     */
    public String getRegisteredName() {
        return registeredName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.registered_name
     *
     * @param registeredName the value for enterprise.registered_name
     *
     * @mbg.generated
     */
    public void setRegisteredName(String registeredName) {
        this.registeredName = registeredName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.registered_no
     *
     * @return the value of enterprise.registered_no
     *
     * @mbg.generated
     */
    public String getRegisteredNo() {
        return registeredNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.registered_no
     *
     * @param registeredNo the value for enterprise.registered_no
     *
     * @mbg.generated
     */
    public void setRegisteredNo(String registeredNo) {
        this.registeredNo = registeredNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.legal_person
     *
     * @return the value of enterprise.legal_person
     *
     * @mbg.generated
     */
    public String getLegalPerson() {
        return legalPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.legal_person
     *
     * @param legalPerson the value for enterprise.legal_person
     *
     * @mbg.generated
     */
    public void setLegalPerson(String legalPerson) {
        this.legalPerson = legalPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.address
     *
     * @return the value of enterprise.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.address
     *
     * @param address the value for enterprise.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.contact_name
     *
     * @return the value of enterprise.contact_name
     *
     * @mbg.generated
     */
    public String getContactName() {
        return contactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.contact_name
     *
     * @param contactName the value for enterprise.contact_name
     *
     * @mbg.generated
     */
    public void setContactName(String contactName) {
        this.contactName = contactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.contact_phone
     *
     * @return the value of enterprise.contact_phone
     *
     * @mbg.generated
     */
    public String getContactPhone() {
        return contactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.contact_phone
     *
     * @param contactPhone the value for enterprise.contact_phone
     *
     * @mbg.generated
     */
    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.email
     *
     * @return the value of enterprise.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.email
     *
     * @param email the value for enterprise.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.logo_url
     *
     * @return the value of enterprise.logo_url
     *
     * @mbg.generated
     */
    public String getLogoUrl() {
        return logoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.logo_url
     *
     * @param logoUrl the value for enterprise.logo_url
     *
     * @mbg.generated
     */
    public void setLogoUrl(String logoUrl) {
        this.logoUrl = logoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.remark
     *
     * @return the value of enterprise.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.remark
     *
     * @param remark the value for enterprise.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.province_id
     *
     * @return the value of enterprise.province_id
     *
     * @mbg.generated
     */
    public String getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.province_id
     *
     * @param provinceId the value for enterprise.province_id
     *
     * @mbg.generated
     */
    public void setProvinceId(String provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.province_name
     *
     * @return the value of enterprise.province_name
     *
     * @mbg.generated
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.province_name
     *
     * @param provinceName the value for enterprise.province_name
     *
     * @mbg.generated
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.city_id
     *
     * @return the value of enterprise.city_id
     *
     * @mbg.generated
     */
    public String getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.city_id
     *
     * @param cityId the value for enterprise.city_id
     *
     * @mbg.generated
     */
    public void setCityId(String cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.city_name
     *
     * @return the value of enterprise.city_name
     *
     * @mbg.generated
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.city_name
     *
     * @param cityName the value for enterprise.city_name
     *
     * @mbg.generated
     */
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.total_short_name
     *
     * @return the value of enterprise.total_short_name
     *
     * @mbg.generated
     */
    public String getTotalShortName() {
        return totalShortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.total_short_name
     *
     * @param totalShortName the value for enterprise.total_short_name
     *
     * @mbg.generated
     */
    public void setTotalShortName(String totalShortName) {
        this.totalShortName = totalShortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.agents_id
     *
     * @return the value of enterprise.agents_id
     *
     * @mbg.generated
     */
    public Integer getAgentsId() {
        return agentsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.agents_id
     *
     * @param agentsId the value for enterprise.agents_id
     *
     * @mbg.generated
     */
    public void setAgentsId(Integer agentsId) {
        this.agentsId = agentsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.created_id
     *
     * @return the value of enterprise.created_id
     *
     * @mbg.generated
     */
    public Integer getCreatedId() {
        return createdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.created_id
     *
     * @param createdId the value for enterprise.created_id
     *
     * @mbg.generated
     */
    public void setCreatedId(Integer createdId) {
        this.createdId = createdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.created_name
     *
     * @return the value of enterprise.created_name
     *
     * @mbg.generated
     */
    public String getCreatedName() {
        return createdName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.created_name
     *
     * @param createdName the value for enterprise.created_name
     *
     * @mbg.generated
     */
    public void setCreatedName(String createdName) {
        this.createdName = createdName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.created_time
     *
     * @return the value of enterprise.created_time
     *
     * @mbg.generated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.created_time
     *
     * @param createdTime the value for enterprise.created_time
     *
     * @mbg.generated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.Column_21
     *
     * @return the value of enterprise.Column_21
     *
     * @mbg.generated
     */
    public String getColumn21() {
        return column21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.Column_21
     *
     * @param column21 the value for enterprise.Column_21
     *
     * @mbg.generated
     */
    public void setColumn21(String column21) {
        this.column21 = column21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.Column_22
     *
     * @return the value of enterprise.Column_22
     *
     * @mbg.generated
     */
    public String getColumn22() {
        return column22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.Column_22
     *
     * @param column22 the value for enterprise.Column_22
     *
     * @mbg.generated
     */
    public void setColumn22(String column22) {
        this.column22 = column22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.Column_23
     *
     * @return the value of enterprise.Column_23
     *
     * @mbg.generated
     */
    public String getColumn23() {
        return column23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.Column_23
     *
     * @param column23 the value for enterprise.Column_23
     *
     * @mbg.generated
     */
    public void setColumn23(String column23) {
        this.column23 = column23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.Column_24
     *
     * @return the value of enterprise.Column_24
     *
     * @mbg.generated
     */
    public Double getColumn24() {
        return column24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.Column_24
     *
     * @param column24 the value for enterprise.Column_24
     *
     * @mbg.generated
     */
    public void setColumn24(Double column24) {
        this.column24 = column24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.Column_25
     *
     * @return the value of enterprise.Column_25
     *
     * @mbg.generated
     */
    public Double getColumn25() {
        return column25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.Column_25
     *
     * @param column25 the value for enterprise.Column_25
     *
     * @mbg.generated
     */
    public void setColumn25(Double column25) {
        this.column25 = column25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.Column_26
     *
     * @return the value of enterprise.Column_26
     *
     * @mbg.generated
     */
    public Double getColumn26() {
        return column26;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.Column_26
     *
     * @param column26 the value for enterprise.Column_26
     *
     * @mbg.generated
     */
    public void setColumn26(Double column26) {
        this.column26 = column26;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.Column_27
     *
     * @return the value of enterprise.Column_27
     *
     * @mbg.generated
     */
    public Double getColumn27() {
        return column27;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.Column_27
     *
     * @param column27 the value for enterprise.Column_27
     *
     * @mbg.generated
     */
    public void setColumn27(Double column27) {
        this.column27 = column27;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.Column_28
     *
     * @return the value of enterprise.Column_28
     *
     * @mbg.generated
     */
    public Byte getColumn28() {
        return column28;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.Column_28
     *
     * @param column28 the value for enterprise.Column_28
     *
     * @mbg.generated
     */
    public void setColumn28(Byte column28) {
        this.column28 = column28;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.Column_29
     *
     * @return the value of enterprise.Column_29
     *
     * @mbg.generated
     */
    public Byte getColumn29() {
        return column29;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.Column_29
     *
     * @param column29 the value for enterprise.Column_29
     *
     * @mbg.generated
     */
    public void setColumn29(Byte column29) {
        this.column29 = column29;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.Column_30
     *
     * @return the value of enterprise.Column_30
     *
     * @mbg.generated
     */
    public Byte getColumn30() {
        return column30;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.Column_30
     *
     * @param column30 the value for enterprise.Column_30
     *
     * @mbg.generated
     */
    public void setColumn30(Byte column30) {
        this.column30 = column30;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.Column_31
     *
     * @return the value of enterprise.Column_31
     *
     * @mbg.generated
     */
    public Byte getColumn31() {
        return column31;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.Column_31
     *
     * @param column31 the value for enterprise.Column_31
     *
     * @mbg.generated
     */
    public void setColumn31(Byte column31) {
        this.column31 = column31;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.protect_amount
     *
     * @return the value of enterprise.protect_amount
     *
     * @mbg.generated
     */
    public Double getProtectAmount() {
        return protectAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.protect_amount
     *
     * @param protectAmount the value for enterprise.protect_amount
     *
     * @mbg.generated
     */
    public void setProtectAmount(Double protectAmount) {
        this.protectAmount = protectAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", enterpriseId=").append(enterpriseId);
        sb.append(", enterpriseName=").append(enterpriseName);
        sb.append(", registeredName=").append(registeredName);
        sb.append(", registeredNo=").append(registeredNo);
        sb.append(", legalPerson=").append(legalPerson);
        sb.append(", address=").append(address);
        sb.append(", contactName=").append(contactName);
        sb.append(", contactPhone=").append(contactPhone);
        sb.append(", email=").append(email);
        sb.append(", logoUrl=").append(logoUrl);
        sb.append(", remark=").append(remark);
        sb.append(", provinceId=").append(provinceId);
        sb.append(", provinceName=").append(provinceName);
        sb.append(", cityId=").append(cityId);
        sb.append(", cityName=").append(cityName);
        sb.append(", totalShortName=").append(totalShortName);
        sb.append(", agentsId=").append(agentsId);
        sb.append(", createdId=").append(createdId);
        sb.append(", createdName=").append(createdName);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", column21=").append(column21);
        sb.append(", column22=").append(column22);
        sb.append(", column23=").append(column23);
        sb.append(", column24=").append(column24);
        sb.append(", column25=").append(column25);
        sb.append(", column26=").append(column26);
        sb.append(", column27=").append(column27);
        sb.append(", column28=").append(column28);
        sb.append(", column29=").append(column29);
        sb.append(", column30=").append(column30);
        sb.append(", column31=").append(column31);
        sb.append(", protectAmount=").append(protectAmount);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}