package com.tuyou.tuyoucrm.vo;

import java.io.Serializable;
import java.util.Date;

public class EnterpriseGradeConfig implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_grade_config.grade_config_id
     *
     * @mbg.generated
     */
    private Integer gradeConfigId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_grade_config.grade_config_name
     *
     * @mbg.generated
     */
    private String gradeConfigName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_grade_config.enterprise_id
     *
     * @mbg.generated
     */
    private Integer enterpriseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_grade_config.enterprise_name
     *
     * @mbg.generated
     */
    private String enterpriseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_grade_config.station_id
     *
     * @mbg.generated
     */
    private Integer stationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_grade_config.station_name
     *
     * @mbg.generated
     */
    private String stationName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_grade_config.gas_integral
     *
     * @mbg.generated
     */
    private Integer gasIntegral;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_grade_config.gas_discount
     *
     * @mbg.generated
     */
    private Double gasDiscount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_grade_config.diesel_integral
     *
     * @mbg.generated
     */
    private Integer dieselIntegral;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_grade_config.diesel_discount
     *
     * @mbg.generated
     */
    private Double dieselDiscount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_grade_config.recharge_integral
     *
     * @mbg.generated
     */
    private Integer rechargeIntegral;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_grade_config.grade_type
     *
     * @mbg.generated
     */
    private Byte gradeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_grade_config.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_grade_config.created_id
     *
     * @mbg.generated
     */
    private Integer createdId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_grade_config.created_time
     *
     * @mbg.generated
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_grade_config.created_name
     *
     * @mbg.generated
     */
    private String createdName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table enterprise_grade_config
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_grade_config.grade_config_id
     *
     * @return the value of enterprise_grade_config.grade_config_id
     *
     * @mbg.generated
     */
    public Integer getGradeConfigId() {
        return gradeConfigId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_grade_config.grade_config_id
     *
     * @param gradeConfigId the value for enterprise_grade_config.grade_config_id
     *
     * @mbg.generated
     */
    public void setGradeConfigId(Integer gradeConfigId) {
        this.gradeConfigId = gradeConfigId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_grade_config.grade_config_name
     *
     * @return the value of enterprise_grade_config.grade_config_name
     *
     * @mbg.generated
     */
    public String getGradeConfigName() {
        return gradeConfigName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_grade_config.grade_config_name
     *
     * @param gradeConfigName the value for enterprise_grade_config.grade_config_name
     *
     * @mbg.generated
     */
    public void setGradeConfigName(String gradeConfigName) {
        this.gradeConfigName = gradeConfigName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_grade_config.enterprise_id
     *
     * @return the value of enterprise_grade_config.enterprise_id
     *
     * @mbg.generated
     */
    public Integer getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_grade_config.enterprise_id
     *
     * @param enterpriseId the value for enterprise_grade_config.enterprise_id
     *
     * @mbg.generated
     */
    public void setEnterpriseId(Integer enterpriseId) {
        this.enterpriseId = enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_grade_config.enterprise_name
     *
     * @return the value of enterprise_grade_config.enterprise_name
     *
     * @mbg.generated
     */
    public String getEnterpriseName() {
        return enterpriseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_grade_config.enterprise_name
     *
     * @param enterpriseName the value for enterprise_grade_config.enterprise_name
     *
     * @mbg.generated
     */
    public void setEnterpriseName(String enterpriseName) {
        this.enterpriseName = enterpriseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_grade_config.station_id
     *
     * @return the value of enterprise_grade_config.station_id
     *
     * @mbg.generated
     */
    public Integer getStationId() {
        return stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_grade_config.station_id
     *
     * @param stationId the value for enterprise_grade_config.station_id
     *
     * @mbg.generated
     */
    public void setStationId(Integer stationId) {
        this.stationId = stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_grade_config.station_name
     *
     * @return the value of enterprise_grade_config.station_name
     *
     * @mbg.generated
     */
    public String getStationName() {
        return stationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_grade_config.station_name
     *
     * @param stationName the value for enterprise_grade_config.station_name
     *
     * @mbg.generated
     */
    public void setStationName(String stationName) {
        this.stationName = stationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_grade_config.gas_integral
     *
     * @return the value of enterprise_grade_config.gas_integral
     *
     * @mbg.generated
     */
    public Integer getGasIntegral() {
        return gasIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_grade_config.gas_integral
     *
     * @param gasIntegral the value for enterprise_grade_config.gas_integral
     *
     * @mbg.generated
     */
    public void setGasIntegral(Integer gasIntegral) {
        this.gasIntegral = gasIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_grade_config.gas_discount
     *
     * @return the value of enterprise_grade_config.gas_discount
     *
     * @mbg.generated
     */
    public Double getGasDiscount() {
        return gasDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_grade_config.gas_discount
     *
     * @param gasDiscount the value for enterprise_grade_config.gas_discount
     *
     * @mbg.generated
     */
    public void setGasDiscount(Double gasDiscount) {
        this.gasDiscount = gasDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_grade_config.diesel_integral
     *
     * @return the value of enterprise_grade_config.diesel_integral
     *
     * @mbg.generated
     */
    public Integer getDieselIntegral() {
        return dieselIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_grade_config.diesel_integral
     *
     * @param dieselIntegral the value for enterprise_grade_config.diesel_integral
     *
     * @mbg.generated
     */
    public void setDieselIntegral(Integer dieselIntegral) {
        this.dieselIntegral = dieselIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_grade_config.diesel_discount
     *
     * @return the value of enterprise_grade_config.diesel_discount
     *
     * @mbg.generated
     */
    public Double getDieselDiscount() {
        return dieselDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_grade_config.diesel_discount
     *
     * @param dieselDiscount the value for enterprise_grade_config.diesel_discount
     *
     * @mbg.generated
     */
    public void setDieselDiscount(Double dieselDiscount) {
        this.dieselDiscount = dieselDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_grade_config.recharge_integral
     *
     * @return the value of enterprise_grade_config.recharge_integral
     *
     * @mbg.generated
     */
    public Integer getRechargeIntegral() {
        return rechargeIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_grade_config.recharge_integral
     *
     * @param rechargeIntegral the value for enterprise_grade_config.recharge_integral
     *
     * @mbg.generated
     */
    public void setRechargeIntegral(Integer rechargeIntegral) {
        this.rechargeIntegral = rechargeIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_grade_config.grade_type
     *
     * @return the value of enterprise_grade_config.grade_type
     *
     * @mbg.generated
     */
    public Byte getGradeType() {
        return gradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_grade_config.grade_type
     *
     * @param gradeType the value for enterprise_grade_config.grade_type
     *
     * @mbg.generated
     */
    public void setGradeType(Byte gradeType) {
        this.gradeType = gradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_grade_config.status
     *
     * @return the value of enterprise_grade_config.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_grade_config.status
     *
     * @param status the value for enterprise_grade_config.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_grade_config.created_id
     *
     * @return the value of enterprise_grade_config.created_id
     *
     * @mbg.generated
     */
    public Integer getCreatedId() {
        return createdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_grade_config.created_id
     *
     * @param createdId the value for enterprise_grade_config.created_id
     *
     * @mbg.generated
     */
    public void setCreatedId(Integer createdId) {
        this.createdId = createdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_grade_config.created_time
     *
     * @return the value of enterprise_grade_config.created_time
     *
     * @mbg.generated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_grade_config.created_time
     *
     * @param createdTime the value for enterprise_grade_config.created_time
     *
     * @mbg.generated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_grade_config.created_name
     *
     * @return the value of enterprise_grade_config.created_name
     *
     * @mbg.generated
     */
    public String getCreatedName() {
        return createdName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_grade_config.created_name
     *
     * @param createdName the value for enterprise_grade_config.created_name
     *
     * @mbg.generated
     */
    public void setCreatedName(String createdName) {
        this.createdName = createdName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_grade_config
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", gradeConfigId=").append(gradeConfigId);
        sb.append(", gradeConfigName=").append(gradeConfigName);
        sb.append(", enterpriseId=").append(enterpriseId);
        sb.append(", enterpriseName=").append(enterpriseName);
        sb.append(", stationId=").append(stationId);
        sb.append(", stationName=").append(stationName);
        sb.append(", gasIntegral=").append(gasIntegral);
        sb.append(", gasDiscount=").append(gasDiscount);
        sb.append(", dieselIntegral=").append(dieselIntegral);
        sb.append(", dieselDiscount=").append(dieselDiscount);
        sb.append(", rechargeIntegral=").append(rechargeIntegral);
        sb.append(", gradeType=").append(gradeType);
        sb.append(", status=").append(status);
        sb.append(", createdId=").append(createdId);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", createdName=").append(createdName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}