package com.tuyou.tuyoucrm.vo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class EnterpriseConfigExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table enterprise_config
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table enterprise_config
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table enterprise_config
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_config
     *
     * @mbg.generated
     */
    public EnterpriseConfigExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_config
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_config
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_config
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_config
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_config
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_config
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_config
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_config
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_config
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_config
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table enterprise_config
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andConfigIdIsNull() {
            addCriterion("config_id is null");
            return (Criteria) this;
        }

        public Criteria andConfigIdIsNotNull() {
            addCriterion("config_id is not null");
            return (Criteria) this;
        }

        public Criteria andConfigIdEqualTo(Integer value) {
            addCriterion("config_id =", value, "configId");
            return (Criteria) this;
        }

        public Criteria andConfigIdNotEqualTo(Integer value) {
            addCriterion("config_id <>", value, "configId");
            return (Criteria) this;
        }

        public Criteria andConfigIdGreaterThan(Integer value) {
            addCriterion("config_id >", value, "configId");
            return (Criteria) this;
        }

        public Criteria andConfigIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("config_id >=", value, "configId");
            return (Criteria) this;
        }

        public Criteria andConfigIdLessThan(Integer value) {
            addCriterion("config_id <", value, "configId");
            return (Criteria) this;
        }

        public Criteria andConfigIdLessThanOrEqualTo(Integer value) {
            addCriterion("config_id <=", value, "configId");
            return (Criteria) this;
        }

        public Criteria andConfigIdIn(List<Integer> values) {
            addCriterion("config_id in", values, "configId");
            return (Criteria) this;
        }

        public Criteria andConfigIdNotIn(List<Integer> values) {
            addCriterion("config_id not in", values, "configId");
            return (Criteria) this;
        }

        public Criteria andConfigIdBetween(Integer value1, Integer value2) {
            addCriterion("config_id between", value1, value2, "configId");
            return (Criteria) this;
        }

        public Criteria andConfigIdNotBetween(Integer value1, Integer value2) {
            addCriterion("config_id not between", value1, value2, "configId");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdIsNull() {
            addCriterion("enterprise_id is null");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdIsNotNull() {
            addCriterion("enterprise_id is not null");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdEqualTo(Integer value) {
            addCriterion("enterprise_id =", value, "enterpriseId");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdNotEqualTo(Integer value) {
            addCriterion("enterprise_id <>", value, "enterpriseId");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdGreaterThan(Integer value) {
            addCriterion("enterprise_id >", value, "enterpriseId");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("enterprise_id >=", value, "enterpriseId");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdLessThan(Integer value) {
            addCriterion("enterprise_id <", value, "enterpriseId");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdLessThanOrEqualTo(Integer value) {
            addCriterion("enterprise_id <=", value, "enterpriseId");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdIn(List<Integer> values) {
            addCriterion("enterprise_id in", values, "enterpriseId");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdNotIn(List<Integer> values) {
            addCriterion("enterprise_id not in", values, "enterpriseId");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdBetween(Integer value1, Integer value2) {
            addCriterion("enterprise_id between", value1, value2, "enterpriseId");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdNotBetween(Integer value1, Integer value2) {
            addCriterion("enterprise_id not between", value1, value2, "enterpriseId");
            return (Criteria) this;
        }

        public Criteria andEnterpriseNameIsNull() {
            addCriterion("enterprise_name is null");
            return (Criteria) this;
        }

        public Criteria andEnterpriseNameIsNotNull() {
            addCriterion("enterprise_name is not null");
            return (Criteria) this;
        }

        public Criteria andEnterpriseNameEqualTo(String value) {
            addCriterion("enterprise_name =", value, "enterpriseName");
            return (Criteria) this;
        }

        public Criteria andEnterpriseNameNotEqualTo(String value) {
            addCriterion("enterprise_name <>", value, "enterpriseName");
            return (Criteria) this;
        }

        public Criteria andEnterpriseNameGreaterThan(String value) {
            addCriterion("enterprise_name >", value, "enterpriseName");
            return (Criteria) this;
        }

        public Criteria andEnterpriseNameGreaterThanOrEqualTo(String value) {
            addCriterion("enterprise_name >=", value, "enterpriseName");
            return (Criteria) this;
        }

        public Criteria andEnterpriseNameLessThan(String value) {
            addCriterion("enterprise_name <", value, "enterpriseName");
            return (Criteria) this;
        }

        public Criteria andEnterpriseNameLessThanOrEqualTo(String value) {
            addCriterion("enterprise_name <=", value, "enterpriseName");
            return (Criteria) this;
        }

        public Criteria andEnterpriseNameLike(String value) {
            addCriterion("enterprise_name like", value, "enterpriseName");
            return (Criteria) this;
        }

        public Criteria andEnterpriseNameNotLike(String value) {
            addCriterion("enterprise_name not like", value, "enterpriseName");
            return (Criteria) this;
        }

        public Criteria andEnterpriseNameIn(List<String> values) {
            addCriterion("enterprise_name in", values, "enterpriseName");
            return (Criteria) this;
        }

        public Criteria andEnterpriseNameNotIn(List<String> values) {
            addCriterion("enterprise_name not in", values, "enterpriseName");
            return (Criteria) this;
        }

        public Criteria andEnterpriseNameBetween(String value1, String value2) {
            addCriterion("enterprise_name between", value1, value2, "enterpriseName");
            return (Criteria) this;
        }

        public Criteria andEnterpriseNameNotBetween(String value1, String value2) {
            addCriterion("enterprise_name not between", value1, value2, "enterpriseName");
            return (Criteria) this;
        }

        public Criteria andCreatedIdIsNull() {
            addCriterion("created_id is null");
            return (Criteria) this;
        }

        public Criteria andCreatedIdIsNotNull() {
            addCriterion("created_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedIdEqualTo(Integer value) {
            addCriterion("created_id =", value, "createdId");
            return (Criteria) this;
        }

        public Criteria andCreatedIdNotEqualTo(Integer value) {
            addCriterion("created_id <>", value, "createdId");
            return (Criteria) this;
        }

        public Criteria andCreatedIdGreaterThan(Integer value) {
            addCriterion("created_id >", value, "createdId");
            return (Criteria) this;
        }

        public Criteria andCreatedIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("created_id >=", value, "createdId");
            return (Criteria) this;
        }

        public Criteria andCreatedIdLessThan(Integer value) {
            addCriterion("created_id <", value, "createdId");
            return (Criteria) this;
        }

        public Criteria andCreatedIdLessThanOrEqualTo(Integer value) {
            addCriterion("created_id <=", value, "createdId");
            return (Criteria) this;
        }

        public Criteria andCreatedIdIn(List<Integer> values) {
            addCriterion("created_id in", values, "createdId");
            return (Criteria) this;
        }

        public Criteria andCreatedIdNotIn(List<Integer> values) {
            addCriterion("created_id not in", values, "createdId");
            return (Criteria) this;
        }

        public Criteria andCreatedIdBetween(Integer value1, Integer value2) {
            addCriterion("created_id between", value1, value2, "createdId");
            return (Criteria) this;
        }

        public Criteria andCreatedIdNotBetween(Integer value1, Integer value2) {
            addCriterion("created_id not between", value1, value2, "createdId");
            return (Criteria) this;
        }

        public Criteria andCreatedNameIsNull() {
            addCriterion("created_name is null");
            return (Criteria) this;
        }

        public Criteria andCreatedNameIsNotNull() {
            addCriterion("created_name is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedNameEqualTo(String value) {
            addCriterion("created_name =", value, "createdName");
            return (Criteria) this;
        }

        public Criteria andCreatedNameNotEqualTo(String value) {
            addCriterion("created_name <>", value, "createdName");
            return (Criteria) this;
        }

        public Criteria andCreatedNameGreaterThan(String value) {
            addCriterion("created_name >", value, "createdName");
            return (Criteria) this;
        }

        public Criteria andCreatedNameGreaterThanOrEqualTo(String value) {
            addCriterion("created_name >=", value, "createdName");
            return (Criteria) this;
        }

        public Criteria andCreatedNameLessThan(String value) {
            addCriterion("created_name <", value, "createdName");
            return (Criteria) this;
        }

        public Criteria andCreatedNameLessThanOrEqualTo(String value) {
            addCriterion("created_name <=", value, "createdName");
            return (Criteria) this;
        }

        public Criteria andCreatedNameLike(String value) {
            addCriterion("created_name like", value, "createdName");
            return (Criteria) this;
        }

        public Criteria andCreatedNameNotLike(String value) {
            addCriterion("created_name not like", value, "createdName");
            return (Criteria) this;
        }

        public Criteria andCreatedNameIn(List<String> values) {
            addCriterion("created_name in", values, "createdName");
            return (Criteria) this;
        }

        public Criteria andCreatedNameNotIn(List<String> values) {
            addCriterion("created_name not in", values, "createdName");
            return (Criteria) this;
        }

        public Criteria andCreatedNameBetween(String value1, String value2) {
            addCriterion("created_name between", value1, value2, "createdName");
            return (Criteria) this;
        }

        public Criteria andCreatedNameNotBetween(String value1, String value2) {
            addCriterion("created_name not between", value1, value2, "createdName");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNull() {
            addCriterion("created_time is null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNotNull() {
            addCriterion("created_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeEqualTo(Date value) {
            addCriterion("created_time =", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotEqualTo(Date value) {
            addCriterion("created_time <>", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThan(Date value) {
            addCriterion("created_time >", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("created_time >=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThan(Date value) {
            addCriterion("created_time <", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThanOrEqualTo(Date value) {
            addCriterion("created_time <=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIn(List<Date> values) {
            addCriterion("created_time in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotIn(List<Date> values) {
            addCriterion("created_time not in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeBetween(Date value1, Date value2) {
            addCriterion("created_time between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotBetween(Date value1, Date value2) {
            addCriterion("created_time not between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andColumn6IsNull() {
            addCriterion("Column_6 is null");
            return (Criteria) this;
        }

        public Criteria andColumn6IsNotNull() {
            addCriterion("Column_6 is not null");
            return (Criteria) this;
        }

        public Criteria andColumn6EqualTo(String value) {
            addCriterion("Column_6 =", value, "column6");
            return (Criteria) this;
        }

        public Criteria andColumn6NotEqualTo(String value) {
            addCriterion("Column_6 <>", value, "column6");
            return (Criteria) this;
        }

        public Criteria andColumn6GreaterThan(String value) {
            addCriterion("Column_6 >", value, "column6");
            return (Criteria) this;
        }

        public Criteria andColumn6GreaterThanOrEqualTo(String value) {
            addCriterion("Column_6 >=", value, "column6");
            return (Criteria) this;
        }

        public Criteria andColumn6LessThan(String value) {
            addCriterion("Column_6 <", value, "column6");
            return (Criteria) this;
        }

        public Criteria andColumn6LessThanOrEqualTo(String value) {
            addCriterion("Column_6 <=", value, "column6");
            return (Criteria) this;
        }

        public Criteria andColumn6Like(String value) {
            addCriterion("Column_6 like", value, "column6");
            return (Criteria) this;
        }

        public Criteria andColumn6NotLike(String value) {
            addCriterion("Column_6 not like", value, "column6");
            return (Criteria) this;
        }

        public Criteria andColumn6In(List<String> values) {
            addCriterion("Column_6 in", values, "column6");
            return (Criteria) this;
        }

        public Criteria andColumn6NotIn(List<String> values) {
            addCriterion("Column_6 not in", values, "column6");
            return (Criteria) this;
        }

        public Criteria andColumn6Between(String value1, String value2) {
            addCriterion("Column_6 between", value1, value2, "column6");
            return (Criteria) this;
        }

        public Criteria andColumn6NotBetween(String value1, String value2) {
            addCriterion("Column_6 not between", value1, value2, "column6");
            return (Criteria) this;
        }

        public Criteria andColumn7IsNull() {
            addCriterion("Column_7 is null");
            return (Criteria) this;
        }

        public Criteria andColumn7IsNotNull() {
            addCriterion("Column_7 is not null");
            return (Criteria) this;
        }

        public Criteria andColumn7EqualTo(String value) {
            addCriterion("Column_7 =", value, "column7");
            return (Criteria) this;
        }

        public Criteria andColumn7NotEqualTo(String value) {
            addCriterion("Column_7 <>", value, "column7");
            return (Criteria) this;
        }

        public Criteria andColumn7GreaterThan(String value) {
            addCriterion("Column_7 >", value, "column7");
            return (Criteria) this;
        }

        public Criteria andColumn7GreaterThanOrEqualTo(String value) {
            addCriterion("Column_7 >=", value, "column7");
            return (Criteria) this;
        }

        public Criteria andColumn7LessThan(String value) {
            addCriterion("Column_7 <", value, "column7");
            return (Criteria) this;
        }

        public Criteria andColumn7LessThanOrEqualTo(String value) {
            addCriterion("Column_7 <=", value, "column7");
            return (Criteria) this;
        }

        public Criteria andColumn7Like(String value) {
            addCriterion("Column_7 like", value, "column7");
            return (Criteria) this;
        }

        public Criteria andColumn7NotLike(String value) {
            addCriterion("Column_7 not like", value, "column7");
            return (Criteria) this;
        }

        public Criteria andColumn7In(List<String> values) {
            addCriterion("Column_7 in", values, "column7");
            return (Criteria) this;
        }

        public Criteria andColumn7NotIn(List<String> values) {
            addCriterion("Column_7 not in", values, "column7");
            return (Criteria) this;
        }

        public Criteria andColumn7Between(String value1, String value2) {
            addCriterion("Column_7 between", value1, value2, "column7");
            return (Criteria) this;
        }

        public Criteria andColumn7NotBetween(String value1, String value2) {
            addCriterion("Column_7 not between", value1, value2, "column7");
            return (Criteria) this;
        }

        public Criteria andColumn8IsNull() {
            addCriterion("Column_8 is null");
            return (Criteria) this;
        }

        public Criteria andColumn8IsNotNull() {
            addCriterion("Column_8 is not null");
            return (Criteria) this;
        }

        public Criteria andColumn8EqualTo(String value) {
            addCriterion("Column_8 =", value, "column8");
            return (Criteria) this;
        }

        public Criteria andColumn8NotEqualTo(String value) {
            addCriterion("Column_8 <>", value, "column8");
            return (Criteria) this;
        }

        public Criteria andColumn8GreaterThan(String value) {
            addCriterion("Column_8 >", value, "column8");
            return (Criteria) this;
        }

        public Criteria andColumn8GreaterThanOrEqualTo(String value) {
            addCriterion("Column_8 >=", value, "column8");
            return (Criteria) this;
        }

        public Criteria andColumn8LessThan(String value) {
            addCriterion("Column_8 <", value, "column8");
            return (Criteria) this;
        }

        public Criteria andColumn8LessThanOrEqualTo(String value) {
            addCriterion("Column_8 <=", value, "column8");
            return (Criteria) this;
        }

        public Criteria andColumn8Like(String value) {
            addCriterion("Column_8 like", value, "column8");
            return (Criteria) this;
        }

        public Criteria andColumn8NotLike(String value) {
            addCriterion("Column_8 not like", value, "column8");
            return (Criteria) this;
        }

        public Criteria andColumn8In(List<String> values) {
            addCriterion("Column_8 in", values, "column8");
            return (Criteria) this;
        }

        public Criteria andColumn8NotIn(List<String> values) {
            addCriterion("Column_8 not in", values, "column8");
            return (Criteria) this;
        }

        public Criteria andColumn8Between(String value1, String value2) {
            addCriterion("Column_8 between", value1, value2, "column8");
            return (Criteria) this;
        }

        public Criteria andColumn8NotBetween(String value1, String value2) {
            addCriterion("Column_8 not between", value1, value2, "column8");
            return (Criteria) this;
        }

        public Criteria andColumn9IsNull() {
            addCriterion("Column_9 is null");
            return (Criteria) this;
        }

        public Criteria andColumn9IsNotNull() {
            addCriterion("Column_9 is not null");
            return (Criteria) this;
        }

        public Criteria andColumn9EqualTo(Byte value) {
            addCriterion("Column_9 =", value, "column9");
            return (Criteria) this;
        }

        public Criteria andColumn9NotEqualTo(Byte value) {
            addCriterion("Column_9 <>", value, "column9");
            return (Criteria) this;
        }

        public Criteria andColumn9GreaterThan(Byte value) {
            addCriterion("Column_9 >", value, "column9");
            return (Criteria) this;
        }

        public Criteria andColumn9GreaterThanOrEqualTo(Byte value) {
            addCriterion("Column_9 >=", value, "column9");
            return (Criteria) this;
        }

        public Criteria andColumn9LessThan(Byte value) {
            addCriterion("Column_9 <", value, "column9");
            return (Criteria) this;
        }

        public Criteria andColumn9LessThanOrEqualTo(Byte value) {
            addCriterion("Column_9 <=", value, "column9");
            return (Criteria) this;
        }

        public Criteria andColumn9In(List<Byte> values) {
            addCriterion("Column_9 in", values, "column9");
            return (Criteria) this;
        }

        public Criteria andColumn9NotIn(List<Byte> values) {
            addCriterion("Column_9 not in", values, "column9");
            return (Criteria) this;
        }

        public Criteria andColumn9Between(Byte value1, Byte value2) {
            addCriterion("Column_9 between", value1, value2, "column9");
            return (Criteria) this;
        }

        public Criteria andColumn9NotBetween(Byte value1, Byte value2) {
            addCriterion("Column_9 not between", value1, value2, "column9");
            return (Criteria) this;
        }

        public Criteria andColumn10IsNull() {
            addCriterion("Column_10 is null");
            return (Criteria) this;
        }

        public Criteria andColumn10IsNotNull() {
            addCriterion("Column_10 is not null");
            return (Criteria) this;
        }

        public Criteria andColumn10EqualTo(Byte value) {
            addCriterion("Column_10 =", value, "column10");
            return (Criteria) this;
        }

        public Criteria andColumn10NotEqualTo(Byte value) {
            addCriterion("Column_10 <>", value, "column10");
            return (Criteria) this;
        }

        public Criteria andColumn10GreaterThan(Byte value) {
            addCriterion("Column_10 >", value, "column10");
            return (Criteria) this;
        }

        public Criteria andColumn10GreaterThanOrEqualTo(Byte value) {
            addCriterion("Column_10 >=", value, "column10");
            return (Criteria) this;
        }

        public Criteria andColumn10LessThan(Byte value) {
            addCriterion("Column_10 <", value, "column10");
            return (Criteria) this;
        }

        public Criteria andColumn10LessThanOrEqualTo(Byte value) {
            addCriterion("Column_10 <=", value, "column10");
            return (Criteria) this;
        }

        public Criteria andColumn10In(List<Byte> values) {
            addCriterion("Column_10 in", values, "column10");
            return (Criteria) this;
        }

        public Criteria andColumn10NotIn(List<Byte> values) {
            addCriterion("Column_10 not in", values, "column10");
            return (Criteria) this;
        }

        public Criteria andColumn10Between(Byte value1, Byte value2) {
            addCriterion("Column_10 between", value1, value2, "column10");
            return (Criteria) this;
        }

        public Criteria andColumn10NotBetween(Byte value1, Byte value2) {
            addCriterion("Column_10 not between", value1, value2, "column10");
            return (Criteria) this;
        }

        public Criteria andColumn11IsNull() {
            addCriterion("Column_11 is null");
            return (Criteria) this;
        }

        public Criteria andColumn11IsNotNull() {
            addCriterion("Column_11 is not null");
            return (Criteria) this;
        }

        public Criteria andColumn11EqualTo(Byte value) {
            addCriterion("Column_11 =", value, "column11");
            return (Criteria) this;
        }

        public Criteria andColumn11NotEqualTo(Byte value) {
            addCriterion("Column_11 <>", value, "column11");
            return (Criteria) this;
        }

        public Criteria andColumn11GreaterThan(Byte value) {
            addCriterion("Column_11 >", value, "column11");
            return (Criteria) this;
        }

        public Criteria andColumn11GreaterThanOrEqualTo(Byte value) {
            addCriterion("Column_11 >=", value, "column11");
            return (Criteria) this;
        }

        public Criteria andColumn11LessThan(Byte value) {
            addCriterion("Column_11 <", value, "column11");
            return (Criteria) this;
        }

        public Criteria andColumn11LessThanOrEqualTo(Byte value) {
            addCriterion("Column_11 <=", value, "column11");
            return (Criteria) this;
        }

        public Criteria andColumn11In(List<Byte> values) {
            addCriterion("Column_11 in", values, "column11");
            return (Criteria) this;
        }

        public Criteria andColumn11NotIn(List<Byte> values) {
            addCriterion("Column_11 not in", values, "column11");
            return (Criteria) this;
        }

        public Criteria andColumn11Between(Byte value1, Byte value2) {
            addCriterion("Column_11 between", value1, value2, "column11");
            return (Criteria) this;
        }

        public Criteria andColumn11NotBetween(Byte value1, Byte value2) {
            addCriterion("Column_11 not between", value1, value2, "column11");
            return (Criteria) this;
        }

        public Criteria andColumn12IsNull() {
            addCriterion("Column_12 is null");
            return (Criteria) this;
        }

        public Criteria andColumn12IsNotNull() {
            addCriterion("Column_12 is not null");
            return (Criteria) this;
        }

        public Criteria andColumn12EqualTo(Byte value) {
            addCriterion("Column_12 =", value, "column12");
            return (Criteria) this;
        }

        public Criteria andColumn12NotEqualTo(Byte value) {
            addCriterion("Column_12 <>", value, "column12");
            return (Criteria) this;
        }

        public Criteria andColumn12GreaterThan(Byte value) {
            addCriterion("Column_12 >", value, "column12");
            return (Criteria) this;
        }

        public Criteria andColumn12GreaterThanOrEqualTo(Byte value) {
            addCriterion("Column_12 >=", value, "column12");
            return (Criteria) this;
        }

        public Criteria andColumn12LessThan(Byte value) {
            addCriterion("Column_12 <", value, "column12");
            return (Criteria) this;
        }

        public Criteria andColumn12LessThanOrEqualTo(Byte value) {
            addCriterion("Column_12 <=", value, "column12");
            return (Criteria) this;
        }

        public Criteria andColumn12In(List<Byte> values) {
            addCriterion("Column_12 in", values, "column12");
            return (Criteria) this;
        }

        public Criteria andColumn12NotIn(List<Byte> values) {
            addCriterion("Column_12 not in", values, "column12");
            return (Criteria) this;
        }

        public Criteria andColumn12Between(Byte value1, Byte value2) {
            addCriterion("Column_12 between", value1, value2, "column12");
            return (Criteria) this;
        }

        public Criteria andColumn12NotBetween(Byte value1, Byte value2) {
            addCriterion("Column_12 not between", value1, value2, "column12");
            return (Criteria) this;
        }

        public Criteria andColumn13IsNull() {
            addCriterion("Column_13 is null");
            return (Criteria) this;
        }

        public Criteria andColumn13IsNotNull() {
            addCriterion("Column_13 is not null");
            return (Criteria) this;
        }

        public Criteria andColumn13EqualTo(Byte value) {
            addCriterion("Column_13 =", value, "column13");
            return (Criteria) this;
        }

        public Criteria andColumn13NotEqualTo(Byte value) {
            addCriterion("Column_13 <>", value, "column13");
            return (Criteria) this;
        }

        public Criteria andColumn13GreaterThan(Byte value) {
            addCriterion("Column_13 >", value, "column13");
            return (Criteria) this;
        }

        public Criteria andColumn13GreaterThanOrEqualTo(Byte value) {
            addCriterion("Column_13 >=", value, "column13");
            return (Criteria) this;
        }

        public Criteria andColumn13LessThan(Byte value) {
            addCriterion("Column_13 <", value, "column13");
            return (Criteria) this;
        }

        public Criteria andColumn13LessThanOrEqualTo(Byte value) {
            addCriterion("Column_13 <=", value, "column13");
            return (Criteria) this;
        }

        public Criteria andColumn13In(List<Byte> values) {
            addCriterion("Column_13 in", values, "column13");
            return (Criteria) this;
        }

        public Criteria andColumn13NotIn(List<Byte> values) {
            addCriterion("Column_13 not in", values, "column13");
            return (Criteria) this;
        }

        public Criteria andColumn13Between(Byte value1, Byte value2) {
            addCriterion("Column_13 between", value1, value2, "column13");
            return (Criteria) this;
        }

        public Criteria andColumn13NotBetween(Byte value1, Byte value2) {
            addCriterion("Column_13 not between", value1, value2, "column13");
            return (Criteria) this;
        }

        public Criteria andColumn14IsNull() {
            addCriterion("Column_14 is null");
            return (Criteria) this;
        }

        public Criteria andColumn14IsNotNull() {
            addCriterion("Column_14 is not null");
            return (Criteria) this;
        }

        public Criteria andColumn14EqualTo(String value) {
            addCriterion("Column_14 =", value, "column14");
            return (Criteria) this;
        }

        public Criteria andColumn14NotEqualTo(String value) {
            addCriterion("Column_14 <>", value, "column14");
            return (Criteria) this;
        }

        public Criteria andColumn14GreaterThan(String value) {
            addCriterion("Column_14 >", value, "column14");
            return (Criteria) this;
        }

        public Criteria andColumn14GreaterThanOrEqualTo(String value) {
            addCriterion("Column_14 >=", value, "column14");
            return (Criteria) this;
        }

        public Criteria andColumn14LessThan(String value) {
            addCriterion("Column_14 <", value, "column14");
            return (Criteria) this;
        }

        public Criteria andColumn14LessThanOrEqualTo(String value) {
            addCriterion("Column_14 <=", value, "column14");
            return (Criteria) this;
        }

        public Criteria andColumn14Like(String value) {
            addCriterion("Column_14 like", value, "column14");
            return (Criteria) this;
        }

        public Criteria andColumn14NotLike(String value) {
            addCriterion("Column_14 not like", value, "column14");
            return (Criteria) this;
        }

        public Criteria andColumn14In(List<String> values) {
            addCriterion("Column_14 in", values, "column14");
            return (Criteria) this;
        }

        public Criteria andColumn14NotIn(List<String> values) {
            addCriterion("Column_14 not in", values, "column14");
            return (Criteria) this;
        }

        public Criteria andColumn14Between(String value1, String value2) {
            addCriterion("Column_14 between", value1, value2, "column14");
            return (Criteria) this;
        }

        public Criteria andColumn14NotBetween(String value1, String value2) {
            addCriterion("Column_14 not between", value1, value2, "column14");
            return (Criteria) this;
        }

        public Criteria andColumn15IsNull() {
            addCriterion("Column_15 is null");
            return (Criteria) this;
        }

        public Criteria andColumn15IsNotNull() {
            addCriterion("Column_15 is not null");
            return (Criteria) this;
        }

        public Criteria andColumn15EqualTo(String value) {
            addCriterion("Column_15 =", value, "column15");
            return (Criteria) this;
        }

        public Criteria andColumn15NotEqualTo(String value) {
            addCriterion("Column_15 <>", value, "column15");
            return (Criteria) this;
        }

        public Criteria andColumn15GreaterThan(String value) {
            addCriterion("Column_15 >", value, "column15");
            return (Criteria) this;
        }

        public Criteria andColumn15GreaterThanOrEqualTo(String value) {
            addCriterion("Column_15 >=", value, "column15");
            return (Criteria) this;
        }

        public Criteria andColumn15LessThan(String value) {
            addCriterion("Column_15 <", value, "column15");
            return (Criteria) this;
        }

        public Criteria andColumn15LessThanOrEqualTo(String value) {
            addCriterion("Column_15 <=", value, "column15");
            return (Criteria) this;
        }

        public Criteria andColumn15Like(String value) {
            addCriterion("Column_15 like", value, "column15");
            return (Criteria) this;
        }

        public Criteria andColumn15NotLike(String value) {
            addCriterion("Column_15 not like", value, "column15");
            return (Criteria) this;
        }

        public Criteria andColumn15In(List<String> values) {
            addCriterion("Column_15 in", values, "column15");
            return (Criteria) this;
        }

        public Criteria andColumn15NotIn(List<String> values) {
            addCriterion("Column_15 not in", values, "column15");
            return (Criteria) this;
        }

        public Criteria andColumn15Between(String value1, String value2) {
            addCriterion("Column_15 between", value1, value2, "column15");
            return (Criteria) this;
        }

        public Criteria andColumn15NotBetween(String value1, String value2) {
            addCriterion("Column_15 not between", value1, value2, "column15");
            return (Criteria) this;
        }

        public Criteria andColumn16IsNull() {
            addCriterion("Column_16 is null");
            return (Criteria) this;
        }

        public Criteria andColumn16IsNotNull() {
            addCriterion("Column_16 is not null");
            return (Criteria) this;
        }

        public Criteria andColumn16EqualTo(Integer value) {
            addCriterion("Column_16 =", value, "column16");
            return (Criteria) this;
        }

        public Criteria andColumn16NotEqualTo(Integer value) {
            addCriterion("Column_16 <>", value, "column16");
            return (Criteria) this;
        }

        public Criteria andColumn16GreaterThan(Integer value) {
            addCriterion("Column_16 >", value, "column16");
            return (Criteria) this;
        }

        public Criteria andColumn16GreaterThanOrEqualTo(Integer value) {
            addCriterion("Column_16 >=", value, "column16");
            return (Criteria) this;
        }

        public Criteria andColumn16LessThan(Integer value) {
            addCriterion("Column_16 <", value, "column16");
            return (Criteria) this;
        }

        public Criteria andColumn16LessThanOrEqualTo(Integer value) {
            addCriterion("Column_16 <=", value, "column16");
            return (Criteria) this;
        }

        public Criteria andColumn16In(List<Integer> values) {
            addCriterion("Column_16 in", values, "column16");
            return (Criteria) this;
        }

        public Criteria andColumn16NotIn(List<Integer> values) {
            addCriterion("Column_16 not in", values, "column16");
            return (Criteria) this;
        }

        public Criteria andColumn16Between(Integer value1, Integer value2) {
            addCriterion("Column_16 between", value1, value2, "column16");
            return (Criteria) this;
        }

        public Criteria andColumn16NotBetween(Integer value1, Integer value2) {
            addCriterion("Column_16 not between", value1, value2, "column16");
            return (Criteria) this;
        }

        public Criteria andColumn17IsNull() {
            addCriterion("Column_17 is null");
            return (Criteria) this;
        }

        public Criteria andColumn17IsNotNull() {
            addCriterion("Column_17 is not null");
            return (Criteria) this;
        }

        public Criteria andColumn17EqualTo(Integer value) {
            addCriterion("Column_17 =", value, "column17");
            return (Criteria) this;
        }

        public Criteria andColumn17NotEqualTo(Integer value) {
            addCriterion("Column_17 <>", value, "column17");
            return (Criteria) this;
        }

        public Criteria andColumn17GreaterThan(Integer value) {
            addCriterion("Column_17 >", value, "column17");
            return (Criteria) this;
        }

        public Criteria andColumn17GreaterThanOrEqualTo(Integer value) {
            addCriterion("Column_17 >=", value, "column17");
            return (Criteria) this;
        }

        public Criteria andColumn17LessThan(Integer value) {
            addCriterion("Column_17 <", value, "column17");
            return (Criteria) this;
        }

        public Criteria andColumn17LessThanOrEqualTo(Integer value) {
            addCriterion("Column_17 <=", value, "column17");
            return (Criteria) this;
        }

        public Criteria andColumn17In(List<Integer> values) {
            addCriterion("Column_17 in", values, "column17");
            return (Criteria) this;
        }

        public Criteria andColumn17NotIn(List<Integer> values) {
            addCriterion("Column_17 not in", values, "column17");
            return (Criteria) this;
        }

        public Criteria andColumn17Between(Integer value1, Integer value2) {
            addCriterion("Column_17 between", value1, value2, "column17");
            return (Criteria) this;
        }

        public Criteria andColumn17NotBetween(Integer value1, Integer value2) {
            addCriterion("Column_17 not between", value1, value2, "column17");
            return (Criteria) this;
        }

        public Criteria andColumn18IsNull() {
            addCriterion("Column_18 is null");
            return (Criteria) this;
        }

        public Criteria andColumn18IsNotNull() {
            addCriterion("Column_18 is not null");
            return (Criteria) this;
        }

        public Criteria andColumn18EqualTo(Integer value) {
            addCriterion("Column_18 =", value, "column18");
            return (Criteria) this;
        }

        public Criteria andColumn18NotEqualTo(Integer value) {
            addCriterion("Column_18 <>", value, "column18");
            return (Criteria) this;
        }

        public Criteria andColumn18GreaterThan(Integer value) {
            addCriterion("Column_18 >", value, "column18");
            return (Criteria) this;
        }

        public Criteria andColumn18GreaterThanOrEqualTo(Integer value) {
            addCriterion("Column_18 >=", value, "column18");
            return (Criteria) this;
        }

        public Criteria andColumn18LessThan(Integer value) {
            addCriterion("Column_18 <", value, "column18");
            return (Criteria) this;
        }

        public Criteria andColumn18LessThanOrEqualTo(Integer value) {
            addCriterion("Column_18 <=", value, "column18");
            return (Criteria) this;
        }

        public Criteria andColumn18In(List<Integer> values) {
            addCriterion("Column_18 in", values, "column18");
            return (Criteria) this;
        }

        public Criteria andColumn18NotIn(List<Integer> values) {
            addCriterion("Column_18 not in", values, "column18");
            return (Criteria) this;
        }

        public Criteria andColumn18Between(Integer value1, Integer value2) {
            addCriterion("Column_18 between", value1, value2, "column18");
            return (Criteria) this;
        }

        public Criteria andColumn18NotBetween(Integer value1, Integer value2) {
            addCriterion("Column_18 not between", value1, value2, "column18");
            return (Criteria) this;
        }

        public Criteria andColumn19IsNull() {
            addCriterion("Column_19 is null");
            return (Criteria) this;
        }

        public Criteria andColumn19IsNotNull() {
            addCriterion("Column_19 is not null");
            return (Criteria) this;
        }

        public Criteria andColumn19EqualTo(Integer value) {
            addCriterion("Column_19 =", value, "column19");
            return (Criteria) this;
        }

        public Criteria andColumn19NotEqualTo(Integer value) {
            addCriterion("Column_19 <>", value, "column19");
            return (Criteria) this;
        }

        public Criteria andColumn19GreaterThan(Integer value) {
            addCriterion("Column_19 >", value, "column19");
            return (Criteria) this;
        }

        public Criteria andColumn19GreaterThanOrEqualTo(Integer value) {
            addCriterion("Column_19 >=", value, "column19");
            return (Criteria) this;
        }

        public Criteria andColumn19LessThan(Integer value) {
            addCriterion("Column_19 <", value, "column19");
            return (Criteria) this;
        }

        public Criteria andColumn19LessThanOrEqualTo(Integer value) {
            addCriterion("Column_19 <=", value, "column19");
            return (Criteria) this;
        }

        public Criteria andColumn19In(List<Integer> values) {
            addCriterion("Column_19 in", values, "column19");
            return (Criteria) this;
        }

        public Criteria andColumn19NotIn(List<Integer> values) {
            addCriterion("Column_19 not in", values, "column19");
            return (Criteria) this;
        }

        public Criteria andColumn19Between(Integer value1, Integer value2) {
            addCriterion("Column_19 between", value1, value2, "column19");
            return (Criteria) this;
        }

        public Criteria andColumn19NotBetween(Integer value1, Integer value2) {
            addCriterion("Column_19 not between", value1, value2, "column19");
            return (Criteria) this;
        }

        public Criteria andColumn20IsNull() {
            addCriterion("Column_20 is null");
            return (Criteria) this;
        }

        public Criteria andColumn20IsNotNull() {
            addCriterion("Column_20 is not null");
            return (Criteria) this;
        }

        public Criteria andColumn20EqualTo(Integer value) {
            addCriterion("Column_20 =", value, "column20");
            return (Criteria) this;
        }

        public Criteria andColumn20NotEqualTo(Integer value) {
            addCriterion("Column_20 <>", value, "column20");
            return (Criteria) this;
        }

        public Criteria andColumn20GreaterThan(Integer value) {
            addCriterion("Column_20 >", value, "column20");
            return (Criteria) this;
        }

        public Criteria andColumn20GreaterThanOrEqualTo(Integer value) {
            addCriterion("Column_20 >=", value, "column20");
            return (Criteria) this;
        }

        public Criteria andColumn20LessThan(Integer value) {
            addCriterion("Column_20 <", value, "column20");
            return (Criteria) this;
        }

        public Criteria andColumn20LessThanOrEqualTo(Integer value) {
            addCriterion("Column_20 <=", value, "column20");
            return (Criteria) this;
        }

        public Criteria andColumn20In(List<Integer> values) {
            addCriterion("Column_20 in", values, "column20");
            return (Criteria) this;
        }

        public Criteria andColumn20NotIn(List<Integer> values) {
            addCriterion("Column_20 not in", values, "column20");
            return (Criteria) this;
        }

        public Criteria andColumn20Between(Integer value1, Integer value2) {
            addCriterion("Column_20 between", value1, value2, "column20");
            return (Criteria) this;
        }

        public Criteria andColumn20NotBetween(Integer value1, Integer value2) {
            addCriterion("Column_20 not between", value1, value2, "column20");
            return (Criteria) this;
        }

        public Criteria andColumn21IsNull() {
            addCriterion("Column_21 is null");
            return (Criteria) this;
        }

        public Criteria andColumn21IsNotNull() {
            addCriterion("Column_21 is not null");
            return (Criteria) this;
        }

        public Criteria andColumn21EqualTo(String value) {
            addCriterion("Column_21 =", value, "column21");
            return (Criteria) this;
        }

        public Criteria andColumn21NotEqualTo(String value) {
            addCriterion("Column_21 <>", value, "column21");
            return (Criteria) this;
        }

        public Criteria andColumn21GreaterThan(String value) {
            addCriterion("Column_21 >", value, "column21");
            return (Criteria) this;
        }

        public Criteria andColumn21GreaterThanOrEqualTo(String value) {
            addCriterion("Column_21 >=", value, "column21");
            return (Criteria) this;
        }

        public Criteria andColumn21LessThan(String value) {
            addCriterion("Column_21 <", value, "column21");
            return (Criteria) this;
        }

        public Criteria andColumn21LessThanOrEqualTo(String value) {
            addCriterion("Column_21 <=", value, "column21");
            return (Criteria) this;
        }

        public Criteria andColumn21Like(String value) {
            addCriterion("Column_21 like", value, "column21");
            return (Criteria) this;
        }

        public Criteria andColumn21NotLike(String value) {
            addCriterion("Column_21 not like", value, "column21");
            return (Criteria) this;
        }

        public Criteria andColumn21In(List<String> values) {
            addCriterion("Column_21 in", values, "column21");
            return (Criteria) this;
        }

        public Criteria andColumn21NotIn(List<String> values) {
            addCriterion("Column_21 not in", values, "column21");
            return (Criteria) this;
        }

        public Criteria andColumn21Between(String value1, String value2) {
            addCriterion("Column_21 between", value1, value2, "column21");
            return (Criteria) this;
        }

        public Criteria andColumn21NotBetween(String value1, String value2) {
            addCriterion("Column_21 not between", value1, value2, "column21");
            return (Criteria) this;
        }

        public Criteria andColumn22IsNull() {
            addCriterion("Column_22 is null");
            return (Criteria) this;
        }

        public Criteria andColumn22IsNotNull() {
            addCriterion("Column_22 is not null");
            return (Criteria) this;
        }

        public Criteria andColumn22EqualTo(String value) {
            addCriterion("Column_22 =", value, "column22");
            return (Criteria) this;
        }

        public Criteria andColumn22NotEqualTo(String value) {
            addCriterion("Column_22 <>", value, "column22");
            return (Criteria) this;
        }

        public Criteria andColumn22GreaterThan(String value) {
            addCriterion("Column_22 >", value, "column22");
            return (Criteria) this;
        }

        public Criteria andColumn22GreaterThanOrEqualTo(String value) {
            addCriterion("Column_22 >=", value, "column22");
            return (Criteria) this;
        }

        public Criteria andColumn22LessThan(String value) {
            addCriterion("Column_22 <", value, "column22");
            return (Criteria) this;
        }

        public Criteria andColumn22LessThanOrEqualTo(String value) {
            addCriterion("Column_22 <=", value, "column22");
            return (Criteria) this;
        }

        public Criteria andColumn22Like(String value) {
            addCriterion("Column_22 like", value, "column22");
            return (Criteria) this;
        }

        public Criteria andColumn22NotLike(String value) {
            addCriterion("Column_22 not like", value, "column22");
            return (Criteria) this;
        }

        public Criteria andColumn22In(List<String> values) {
            addCriterion("Column_22 in", values, "column22");
            return (Criteria) this;
        }

        public Criteria andColumn22NotIn(List<String> values) {
            addCriterion("Column_22 not in", values, "column22");
            return (Criteria) this;
        }

        public Criteria andColumn22Between(String value1, String value2) {
            addCriterion("Column_22 between", value1, value2, "column22");
            return (Criteria) this;
        }

        public Criteria andColumn22NotBetween(String value1, String value2) {
            addCriterion("Column_22 not between", value1, value2, "column22");
            return (Criteria) this;
        }

        public Criteria andColumn23IsNull() {
            addCriterion("Column_23 is null");
            return (Criteria) this;
        }

        public Criteria andColumn23IsNotNull() {
            addCriterion("Column_23 is not null");
            return (Criteria) this;
        }

        public Criteria andColumn23EqualTo(String value) {
            addCriterion("Column_23 =", value, "column23");
            return (Criteria) this;
        }

        public Criteria andColumn23NotEqualTo(String value) {
            addCriterion("Column_23 <>", value, "column23");
            return (Criteria) this;
        }

        public Criteria andColumn23GreaterThan(String value) {
            addCriterion("Column_23 >", value, "column23");
            return (Criteria) this;
        }

        public Criteria andColumn23GreaterThanOrEqualTo(String value) {
            addCriterion("Column_23 >=", value, "column23");
            return (Criteria) this;
        }

        public Criteria andColumn23LessThan(String value) {
            addCriterion("Column_23 <", value, "column23");
            return (Criteria) this;
        }

        public Criteria andColumn23LessThanOrEqualTo(String value) {
            addCriterion("Column_23 <=", value, "column23");
            return (Criteria) this;
        }

        public Criteria andColumn23Like(String value) {
            addCriterion("Column_23 like", value, "column23");
            return (Criteria) this;
        }

        public Criteria andColumn23NotLike(String value) {
            addCriterion("Column_23 not like", value, "column23");
            return (Criteria) this;
        }

        public Criteria andColumn23In(List<String> values) {
            addCriterion("Column_23 in", values, "column23");
            return (Criteria) this;
        }

        public Criteria andColumn23NotIn(List<String> values) {
            addCriterion("Column_23 not in", values, "column23");
            return (Criteria) this;
        }

        public Criteria andColumn23Between(String value1, String value2) {
            addCriterion("Column_23 between", value1, value2, "column23");
            return (Criteria) this;
        }

        public Criteria andColumn23NotBetween(String value1, String value2) {
            addCriterion("Column_23 not between", value1, value2, "column23");
            return (Criteria) this;
        }

        public Criteria andColumn24IsNull() {
            addCriterion("Column_24 is null");
            return (Criteria) this;
        }

        public Criteria andColumn24IsNotNull() {
            addCriterion("Column_24 is not null");
            return (Criteria) this;
        }

        public Criteria andColumn24EqualTo(String value) {
            addCriterion("Column_24 =", value, "column24");
            return (Criteria) this;
        }

        public Criteria andColumn24NotEqualTo(String value) {
            addCriterion("Column_24 <>", value, "column24");
            return (Criteria) this;
        }

        public Criteria andColumn24GreaterThan(String value) {
            addCriterion("Column_24 >", value, "column24");
            return (Criteria) this;
        }

        public Criteria andColumn24GreaterThanOrEqualTo(String value) {
            addCriterion("Column_24 >=", value, "column24");
            return (Criteria) this;
        }

        public Criteria andColumn24LessThan(String value) {
            addCriterion("Column_24 <", value, "column24");
            return (Criteria) this;
        }

        public Criteria andColumn24LessThanOrEqualTo(String value) {
            addCriterion("Column_24 <=", value, "column24");
            return (Criteria) this;
        }

        public Criteria andColumn24Like(String value) {
            addCriterion("Column_24 like", value, "column24");
            return (Criteria) this;
        }

        public Criteria andColumn24NotLike(String value) {
            addCriterion("Column_24 not like", value, "column24");
            return (Criteria) this;
        }

        public Criteria andColumn24In(List<String> values) {
            addCriterion("Column_24 in", values, "column24");
            return (Criteria) this;
        }

        public Criteria andColumn24NotIn(List<String> values) {
            addCriterion("Column_24 not in", values, "column24");
            return (Criteria) this;
        }

        public Criteria andColumn24Between(String value1, String value2) {
            addCriterion("Column_24 between", value1, value2, "column24");
            return (Criteria) this;
        }

        public Criteria andColumn24NotBetween(String value1, String value2) {
            addCriterion("Column_24 not between", value1, value2, "column24");
            return (Criteria) this;
        }

        public Criteria andColumn25IsNull() {
            addCriterion("Column_25 is null");
            return (Criteria) this;
        }

        public Criteria andColumn25IsNotNull() {
            addCriterion("Column_25 is not null");
            return (Criteria) this;
        }

        public Criteria andColumn25EqualTo(Double value) {
            addCriterion("Column_25 =", value, "column25");
            return (Criteria) this;
        }

        public Criteria andColumn25NotEqualTo(Double value) {
            addCriterion("Column_25 <>", value, "column25");
            return (Criteria) this;
        }

        public Criteria andColumn25GreaterThan(Double value) {
            addCriterion("Column_25 >", value, "column25");
            return (Criteria) this;
        }

        public Criteria andColumn25GreaterThanOrEqualTo(Double value) {
            addCriterion("Column_25 >=", value, "column25");
            return (Criteria) this;
        }

        public Criteria andColumn25LessThan(Double value) {
            addCriterion("Column_25 <", value, "column25");
            return (Criteria) this;
        }

        public Criteria andColumn25LessThanOrEqualTo(Double value) {
            addCriterion("Column_25 <=", value, "column25");
            return (Criteria) this;
        }

        public Criteria andColumn25In(List<Double> values) {
            addCriterion("Column_25 in", values, "column25");
            return (Criteria) this;
        }

        public Criteria andColumn25NotIn(List<Double> values) {
            addCriterion("Column_25 not in", values, "column25");
            return (Criteria) this;
        }

        public Criteria andColumn25Between(Double value1, Double value2) {
            addCriterion("Column_25 between", value1, value2, "column25");
            return (Criteria) this;
        }

        public Criteria andColumn25NotBetween(Double value1, Double value2) {
            addCriterion("Column_25 not between", value1, value2, "column25");
            return (Criteria) this;
        }

        public Criteria andColumn26IsNull() {
            addCriterion("Column_26 is null");
            return (Criteria) this;
        }

        public Criteria andColumn26IsNotNull() {
            addCriterion("Column_26 is not null");
            return (Criteria) this;
        }

        public Criteria andColumn26EqualTo(Double value) {
            addCriterion("Column_26 =", value, "column26");
            return (Criteria) this;
        }

        public Criteria andColumn26NotEqualTo(Double value) {
            addCriterion("Column_26 <>", value, "column26");
            return (Criteria) this;
        }

        public Criteria andColumn26GreaterThan(Double value) {
            addCriterion("Column_26 >", value, "column26");
            return (Criteria) this;
        }

        public Criteria andColumn26GreaterThanOrEqualTo(Double value) {
            addCriterion("Column_26 >=", value, "column26");
            return (Criteria) this;
        }

        public Criteria andColumn26LessThan(Double value) {
            addCriterion("Column_26 <", value, "column26");
            return (Criteria) this;
        }

        public Criteria andColumn26LessThanOrEqualTo(Double value) {
            addCriterion("Column_26 <=", value, "column26");
            return (Criteria) this;
        }

        public Criteria andColumn26In(List<Double> values) {
            addCriterion("Column_26 in", values, "column26");
            return (Criteria) this;
        }

        public Criteria andColumn26NotIn(List<Double> values) {
            addCriterion("Column_26 not in", values, "column26");
            return (Criteria) this;
        }

        public Criteria andColumn26Between(Double value1, Double value2) {
            addCriterion("Column_26 between", value1, value2, "column26");
            return (Criteria) this;
        }

        public Criteria andColumn26NotBetween(Double value1, Double value2) {
            addCriterion("Column_26 not between", value1, value2, "column26");
            return (Criteria) this;
        }

        public Criteria andColumn27IsNull() {
            addCriterion("Column_27 is null");
            return (Criteria) this;
        }

        public Criteria andColumn27IsNotNull() {
            addCriterion("Column_27 is not null");
            return (Criteria) this;
        }

        public Criteria andColumn27EqualTo(Double value) {
            addCriterion("Column_27 =", value, "column27");
            return (Criteria) this;
        }

        public Criteria andColumn27NotEqualTo(Double value) {
            addCriterion("Column_27 <>", value, "column27");
            return (Criteria) this;
        }

        public Criteria andColumn27GreaterThan(Double value) {
            addCriterion("Column_27 >", value, "column27");
            return (Criteria) this;
        }

        public Criteria andColumn27GreaterThanOrEqualTo(Double value) {
            addCriterion("Column_27 >=", value, "column27");
            return (Criteria) this;
        }

        public Criteria andColumn27LessThan(Double value) {
            addCriterion("Column_27 <", value, "column27");
            return (Criteria) this;
        }

        public Criteria andColumn27LessThanOrEqualTo(Double value) {
            addCriterion("Column_27 <=", value, "column27");
            return (Criteria) this;
        }

        public Criteria andColumn27In(List<Double> values) {
            addCriterion("Column_27 in", values, "column27");
            return (Criteria) this;
        }

        public Criteria andColumn27NotIn(List<Double> values) {
            addCriterion("Column_27 not in", values, "column27");
            return (Criteria) this;
        }

        public Criteria andColumn27Between(Double value1, Double value2) {
            addCriterion("Column_27 between", value1, value2, "column27");
            return (Criteria) this;
        }

        public Criteria andColumn27NotBetween(Double value1, Double value2) {
            addCriterion("Column_27 not between", value1, value2, "column27");
            return (Criteria) this;
        }

        public Criteria andColumn28IsNull() {
            addCriterion("Column_28 is null");
            return (Criteria) this;
        }

        public Criteria andColumn28IsNotNull() {
            addCriterion("Column_28 is not null");
            return (Criteria) this;
        }

        public Criteria andColumn28EqualTo(Integer value) {
            addCriterion("Column_28 =", value, "column28");
            return (Criteria) this;
        }

        public Criteria andColumn28NotEqualTo(Integer value) {
            addCriterion("Column_28 <>", value, "column28");
            return (Criteria) this;
        }

        public Criteria andColumn28GreaterThan(Integer value) {
            addCriterion("Column_28 >", value, "column28");
            return (Criteria) this;
        }

        public Criteria andColumn28GreaterThanOrEqualTo(Integer value) {
            addCriterion("Column_28 >=", value, "column28");
            return (Criteria) this;
        }

        public Criteria andColumn28LessThan(Integer value) {
            addCriterion("Column_28 <", value, "column28");
            return (Criteria) this;
        }

        public Criteria andColumn28LessThanOrEqualTo(Integer value) {
            addCriterion("Column_28 <=", value, "column28");
            return (Criteria) this;
        }

        public Criteria andColumn28In(List<Integer> values) {
            addCriterion("Column_28 in", values, "column28");
            return (Criteria) this;
        }

        public Criteria andColumn28NotIn(List<Integer> values) {
            addCriterion("Column_28 not in", values, "column28");
            return (Criteria) this;
        }

        public Criteria andColumn28Between(Integer value1, Integer value2) {
            addCriterion("Column_28 between", value1, value2, "column28");
            return (Criteria) this;
        }

        public Criteria andColumn28NotBetween(Integer value1, Integer value2) {
            addCriterion("Column_28 not between", value1, value2, "column28");
            return (Criteria) this;
        }

        public Criteria andColumn29IsNull() {
            addCriterion("Column_29 is null");
            return (Criteria) this;
        }

        public Criteria andColumn29IsNotNull() {
            addCriterion("Column_29 is not null");
            return (Criteria) this;
        }

        public Criteria andColumn29EqualTo(Integer value) {
            addCriterion("Column_29 =", value, "column29");
            return (Criteria) this;
        }

        public Criteria andColumn29NotEqualTo(Integer value) {
            addCriterion("Column_29 <>", value, "column29");
            return (Criteria) this;
        }

        public Criteria andColumn29GreaterThan(Integer value) {
            addCriterion("Column_29 >", value, "column29");
            return (Criteria) this;
        }

        public Criteria andColumn29GreaterThanOrEqualTo(Integer value) {
            addCriterion("Column_29 >=", value, "column29");
            return (Criteria) this;
        }

        public Criteria andColumn29LessThan(Integer value) {
            addCriterion("Column_29 <", value, "column29");
            return (Criteria) this;
        }

        public Criteria andColumn29LessThanOrEqualTo(Integer value) {
            addCriterion("Column_29 <=", value, "column29");
            return (Criteria) this;
        }

        public Criteria andColumn29In(List<Integer> values) {
            addCriterion("Column_29 in", values, "column29");
            return (Criteria) this;
        }

        public Criteria andColumn29NotIn(List<Integer> values) {
            addCriterion("Column_29 not in", values, "column29");
            return (Criteria) this;
        }

        public Criteria andColumn29Between(Integer value1, Integer value2) {
            addCriterion("Column_29 between", value1, value2, "column29");
            return (Criteria) this;
        }

        public Criteria andColumn29NotBetween(Integer value1, Integer value2) {
            addCriterion("Column_29 not between", value1, value2, "column29");
            return (Criteria) this;
        }

        public Criteria andColumn30IsNull() {
            addCriterion("Column_30 is null");
            return (Criteria) this;
        }

        public Criteria andColumn30IsNotNull() {
            addCriterion("Column_30 is not null");
            return (Criteria) this;
        }

        public Criteria andColumn30EqualTo(Integer value) {
            addCriterion("Column_30 =", value, "column30");
            return (Criteria) this;
        }

        public Criteria andColumn30NotEqualTo(Integer value) {
            addCriterion("Column_30 <>", value, "column30");
            return (Criteria) this;
        }

        public Criteria andColumn30GreaterThan(Integer value) {
            addCriterion("Column_30 >", value, "column30");
            return (Criteria) this;
        }

        public Criteria andColumn30GreaterThanOrEqualTo(Integer value) {
            addCriterion("Column_30 >=", value, "column30");
            return (Criteria) this;
        }

        public Criteria andColumn30LessThan(Integer value) {
            addCriterion("Column_30 <", value, "column30");
            return (Criteria) this;
        }

        public Criteria andColumn30LessThanOrEqualTo(Integer value) {
            addCriterion("Column_30 <=", value, "column30");
            return (Criteria) this;
        }

        public Criteria andColumn30In(List<Integer> values) {
            addCriterion("Column_30 in", values, "column30");
            return (Criteria) this;
        }

        public Criteria andColumn30NotIn(List<Integer> values) {
            addCriterion("Column_30 not in", values, "column30");
            return (Criteria) this;
        }

        public Criteria andColumn30Between(Integer value1, Integer value2) {
            addCriterion("Column_30 between", value1, value2, "column30");
            return (Criteria) this;
        }

        public Criteria andColumn30NotBetween(Integer value1, Integer value2) {
            addCriterion("Column_30 not between", value1, value2, "column30");
            return (Criteria) this;
        }

        public Criteria andColumn31IsNull() {
            addCriterion("Column_31 is null");
            return (Criteria) this;
        }

        public Criteria andColumn31IsNotNull() {
            addCriterion("Column_31 is not null");
            return (Criteria) this;
        }

        public Criteria andColumn31EqualTo(Integer value) {
            addCriterion("Column_31 =", value, "column31");
            return (Criteria) this;
        }

        public Criteria andColumn31NotEqualTo(Integer value) {
            addCriterion("Column_31 <>", value, "column31");
            return (Criteria) this;
        }

        public Criteria andColumn31GreaterThan(Integer value) {
            addCriterion("Column_31 >", value, "column31");
            return (Criteria) this;
        }

        public Criteria andColumn31GreaterThanOrEqualTo(Integer value) {
            addCriterion("Column_31 >=", value, "column31");
            return (Criteria) this;
        }

        public Criteria andColumn31LessThan(Integer value) {
            addCriterion("Column_31 <", value, "column31");
            return (Criteria) this;
        }

        public Criteria andColumn31LessThanOrEqualTo(Integer value) {
            addCriterion("Column_31 <=", value, "column31");
            return (Criteria) this;
        }

        public Criteria andColumn31In(List<Integer> values) {
            addCriterion("Column_31 in", values, "column31");
            return (Criteria) this;
        }

        public Criteria andColumn31NotIn(List<Integer> values) {
            addCriterion("Column_31 not in", values, "column31");
            return (Criteria) this;
        }

        public Criteria andColumn31Between(Integer value1, Integer value2) {
            addCriterion("Column_31 between", value1, value2, "column31");
            return (Criteria) this;
        }

        public Criteria andColumn31NotBetween(Integer value1, Integer value2) {
            addCriterion("Column_31 not between", value1, value2, "column31");
            return (Criteria) this;
        }

        public Criteria andColumn32IsNull() {
            addCriterion("Column_32 is null");
            return (Criteria) this;
        }

        public Criteria andColumn32IsNotNull() {
            addCriterion("Column_32 is not null");
            return (Criteria) this;
        }

        public Criteria andColumn32EqualTo(Integer value) {
            addCriterion("Column_32 =", value, "column32");
            return (Criteria) this;
        }

        public Criteria andColumn32NotEqualTo(Integer value) {
            addCriterion("Column_32 <>", value, "column32");
            return (Criteria) this;
        }

        public Criteria andColumn32GreaterThan(Integer value) {
            addCriterion("Column_32 >", value, "column32");
            return (Criteria) this;
        }

        public Criteria andColumn32GreaterThanOrEqualTo(Integer value) {
            addCriterion("Column_32 >=", value, "column32");
            return (Criteria) this;
        }

        public Criteria andColumn32LessThan(Integer value) {
            addCriterion("Column_32 <", value, "column32");
            return (Criteria) this;
        }

        public Criteria andColumn32LessThanOrEqualTo(Integer value) {
            addCriterion("Column_32 <=", value, "column32");
            return (Criteria) this;
        }

        public Criteria andColumn32In(List<Integer> values) {
            addCriterion("Column_32 in", values, "column32");
            return (Criteria) this;
        }

        public Criteria andColumn32NotIn(List<Integer> values) {
            addCriterion("Column_32 not in", values, "column32");
            return (Criteria) this;
        }

        public Criteria andColumn32Between(Integer value1, Integer value2) {
            addCriterion("Column_32 between", value1, value2, "column32");
            return (Criteria) this;
        }

        public Criteria andColumn32NotBetween(Integer value1, Integer value2) {
            addCriterion("Column_32 not between", value1, value2, "column32");
            return (Criteria) this;
        }

        public Criteria andColumn33IsNull() {
            addCriterion("Column_33 is null");
            return (Criteria) this;
        }

        public Criteria andColumn33IsNotNull() {
            addCriterion("Column_33 is not null");
            return (Criteria) this;
        }

        public Criteria andColumn33EqualTo(Integer value) {
            addCriterion("Column_33 =", value, "column33");
            return (Criteria) this;
        }

        public Criteria andColumn33NotEqualTo(Integer value) {
            addCriterion("Column_33 <>", value, "column33");
            return (Criteria) this;
        }

        public Criteria andColumn33GreaterThan(Integer value) {
            addCriterion("Column_33 >", value, "column33");
            return (Criteria) this;
        }

        public Criteria andColumn33GreaterThanOrEqualTo(Integer value) {
            addCriterion("Column_33 >=", value, "column33");
            return (Criteria) this;
        }

        public Criteria andColumn33LessThan(Integer value) {
            addCriterion("Column_33 <", value, "column33");
            return (Criteria) this;
        }

        public Criteria andColumn33LessThanOrEqualTo(Integer value) {
            addCriterion("Column_33 <=", value, "column33");
            return (Criteria) this;
        }

        public Criteria andColumn33In(List<Integer> values) {
            addCriterion("Column_33 in", values, "column33");
            return (Criteria) this;
        }

        public Criteria andColumn33NotIn(List<Integer> values) {
            addCriterion("Column_33 not in", values, "column33");
            return (Criteria) this;
        }

        public Criteria andColumn33Between(Integer value1, Integer value2) {
            addCriterion("Column_33 between", value1, value2, "column33");
            return (Criteria) this;
        }

        public Criteria andColumn33NotBetween(Integer value1, Integer value2) {
            addCriterion("Column_33 not between", value1, value2, "column33");
            return (Criteria) this;
        }

        public Criteria andColumn34IsNull() {
            addCriterion("Column_34 is null");
            return (Criteria) this;
        }

        public Criteria andColumn34IsNotNull() {
            addCriterion("Column_34 is not null");
            return (Criteria) this;
        }

        public Criteria andColumn34EqualTo(Double value) {
            addCriterion("Column_34 =", value, "column34");
            return (Criteria) this;
        }

        public Criteria andColumn34NotEqualTo(Double value) {
            addCriterion("Column_34 <>", value, "column34");
            return (Criteria) this;
        }

        public Criteria andColumn34GreaterThan(Double value) {
            addCriterion("Column_34 >", value, "column34");
            return (Criteria) this;
        }

        public Criteria andColumn34GreaterThanOrEqualTo(Double value) {
            addCriterion("Column_34 >=", value, "column34");
            return (Criteria) this;
        }

        public Criteria andColumn34LessThan(Double value) {
            addCriterion("Column_34 <", value, "column34");
            return (Criteria) this;
        }

        public Criteria andColumn34LessThanOrEqualTo(Double value) {
            addCriterion("Column_34 <=", value, "column34");
            return (Criteria) this;
        }

        public Criteria andColumn34In(List<Double> values) {
            addCriterion("Column_34 in", values, "column34");
            return (Criteria) this;
        }

        public Criteria andColumn34NotIn(List<Double> values) {
            addCriterion("Column_34 not in", values, "column34");
            return (Criteria) this;
        }

        public Criteria andColumn34Between(Double value1, Double value2) {
            addCriterion("Column_34 between", value1, value2, "column34");
            return (Criteria) this;
        }

        public Criteria andColumn34NotBetween(Double value1, Double value2) {
            addCriterion("Column_34 not between", value1, value2, "column34");
            return (Criteria) this;
        }

        public Criteria andColumn35IsNull() {
            addCriterion("Column_35 is null");
            return (Criteria) this;
        }

        public Criteria andColumn35IsNotNull() {
            addCriterion("Column_35 is not null");
            return (Criteria) this;
        }

        public Criteria andColumn35EqualTo(Double value) {
            addCriterion("Column_35 =", value, "column35");
            return (Criteria) this;
        }

        public Criteria andColumn35NotEqualTo(Double value) {
            addCriterion("Column_35 <>", value, "column35");
            return (Criteria) this;
        }

        public Criteria andColumn35GreaterThan(Double value) {
            addCriterion("Column_35 >", value, "column35");
            return (Criteria) this;
        }

        public Criteria andColumn35GreaterThanOrEqualTo(Double value) {
            addCriterion("Column_35 >=", value, "column35");
            return (Criteria) this;
        }

        public Criteria andColumn35LessThan(Double value) {
            addCriterion("Column_35 <", value, "column35");
            return (Criteria) this;
        }

        public Criteria andColumn35LessThanOrEqualTo(Double value) {
            addCriterion("Column_35 <=", value, "column35");
            return (Criteria) this;
        }

        public Criteria andColumn35In(List<Double> values) {
            addCriterion("Column_35 in", values, "column35");
            return (Criteria) this;
        }

        public Criteria andColumn35NotIn(List<Double> values) {
            addCriterion("Column_35 not in", values, "column35");
            return (Criteria) this;
        }

        public Criteria andColumn35Between(Double value1, Double value2) {
            addCriterion("Column_35 between", value1, value2, "column35");
            return (Criteria) this;
        }

        public Criteria andColumn35NotBetween(Double value1, Double value2) {
            addCriterion("Column_35 not between", value1, value2, "column35");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table enterprise_config
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table enterprise_config
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}