package com.tuyou.tuyoucrm.vo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class EnterpriseGradeConfigExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table enterprise_grade_config
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table enterprise_grade_config
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table enterprise_grade_config
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_grade_config
     *
     * @mbg.generated
     */
    public EnterpriseGradeConfigExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_grade_config
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_grade_config
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_grade_config
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_grade_config
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_grade_config
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_grade_config
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_grade_config
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_grade_config
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_grade_config
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_grade_config
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table enterprise_grade_config
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andGradeConfigIdIsNull() {
            addCriterion("grade_config_id is null");
            return (Criteria) this;
        }

        public Criteria andGradeConfigIdIsNotNull() {
            addCriterion("grade_config_id is not null");
            return (Criteria) this;
        }

        public Criteria andGradeConfigIdEqualTo(Integer value) {
            addCriterion("grade_config_id =", value, "gradeConfigId");
            return (Criteria) this;
        }

        public Criteria andGradeConfigIdNotEqualTo(Integer value) {
            addCriterion("grade_config_id <>", value, "gradeConfigId");
            return (Criteria) this;
        }

        public Criteria andGradeConfigIdGreaterThan(Integer value) {
            addCriterion("grade_config_id >", value, "gradeConfigId");
            return (Criteria) this;
        }

        public Criteria andGradeConfigIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("grade_config_id >=", value, "gradeConfigId");
            return (Criteria) this;
        }

        public Criteria andGradeConfigIdLessThan(Integer value) {
            addCriterion("grade_config_id <", value, "gradeConfigId");
            return (Criteria) this;
        }

        public Criteria andGradeConfigIdLessThanOrEqualTo(Integer value) {
            addCriterion("grade_config_id <=", value, "gradeConfigId");
            return (Criteria) this;
        }

        public Criteria andGradeConfigIdIn(List<Integer> values) {
            addCriterion("grade_config_id in", values, "gradeConfigId");
            return (Criteria) this;
        }

        public Criteria andGradeConfigIdNotIn(List<Integer> values) {
            addCriterion("grade_config_id not in", values, "gradeConfigId");
            return (Criteria) this;
        }

        public Criteria andGradeConfigIdBetween(Integer value1, Integer value2) {
            addCriterion("grade_config_id between", value1, value2, "gradeConfigId");
            return (Criteria) this;
        }

        public Criteria andGradeConfigIdNotBetween(Integer value1, Integer value2) {
            addCriterion("grade_config_id not between", value1, value2, "gradeConfigId");
            return (Criteria) this;
        }

        public Criteria andGradeConfigNameIsNull() {
            addCriterion("grade_config_name is null");
            return (Criteria) this;
        }

        public Criteria andGradeConfigNameIsNotNull() {
            addCriterion("grade_config_name is not null");
            return (Criteria) this;
        }

        public Criteria andGradeConfigNameEqualTo(String value) {
            addCriterion("grade_config_name =", value, "gradeConfigName");
            return (Criteria) this;
        }

        public Criteria andGradeConfigNameNotEqualTo(String value) {
            addCriterion("grade_config_name <>", value, "gradeConfigName");
            return (Criteria) this;
        }

        public Criteria andGradeConfigNameGreaterThan(String value) {
            addCriterion("grade_config_name >", value, "gradeConfigName");
            return (Criteria) this;
        }

        public Criteria andGradeConfigNameGreaterThanOrEqualTo(String value) {
            addCriterion("grade_config_name >=", value, "gradeConfigName");
            return (Criteria) this;
        }

        public Criteria andGradeConfigNameLessThan(String value) {
            addCriterion("grade_config_name <", value, "gradeConfigName");
            return (Criteria) this;
        }

        public Criteria andGradeConfigNameLessThanOrEqualTo(String value) {
            addCriterion("grade_config_name <=", value, "gradeConfigName");
            return (Criteria) this;
        }

        public Criteria andGradeConfigNameLike(String value) {
            addCriterion("grade_config_name like", value, "gradeConfigName");
            return (Criteria) this;
        }

        public Criteria andGradeConfigNameNotLike(String value) {
            addCriterion("grade_config_name not like", value, "gradeConfigName");
            return (Criteria) this;
        }

        public Criteria andGradeConfigNameIn(List<String> values) {
            addCriterion("grade_config_name in", values, "gradeConfigName");
            return (Criteria) this;
        }

        public Criteria andGradeConfigNameNotIn(List<String> values) {
            addCriterion("grade_config_name not in", values, "gradeConfigName");
            return (Criteria) this;
        }

        public Criteria andGradeConfigNameBetween(String value1, String value2) {
            addCriterion("grade_config_name between", value1, value2, "gradeConfigName");
            return (Criteria) this;
        }

        public Criteria andGradeConfigNameNotBetween(String value1, String value2) {
            addCriterion("grade_config_name not between", value1, value2, "gradeConfigName");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdIsNull() {
            addCriterion("enterprise_id is null");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdIsNotNull() {
            addCriterion("enterprise_id is not null");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdEqualTo(Integer value) {
            addCriterion("enterprise_id =", value, "enterpriseId");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdNotEqualTo(Integer value) {
            addCriterion("enterprise_id <>", value, "enterpriseId");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdGreaterThan(Integer value) {
            addCriterion("enterprise_id >", value, "enterpriseId");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("enterprise_id >=", value, "enterpriseId");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdLessThan(Integer value) {
            addCriterion("enterprise_id <", value, "enterpriseId");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdLessThanOrEqualTo(Integer value) {
            addCriterion("enterprise_id <=", value, "enterpriseId");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdIn(List<Integer> values) {
            addCriterion("enterprise_id in", values, "enterpriseId");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdNotIn(List<Integer> values) {
            addCriterion("enterprise_id not in", values, "enterpriseId");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdBetween(Integer value1, Integer value2) {
            addCriterion("enterprise_id between", value1, value2, "enterpriseId");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdNotBetween(Integer value1, Integer value2) {
            addCriterion("enterprise_id not between", value1, value2, "enterpriseId");
            return (Criteria) this;
        }

        public Criteria andEnterpriseNameIsNull() {
            addCriterion("enterprise_name is null");
            return (Criteria) this;
        }

        public Criteria andEnterpriseNameIsNotNull() {
            addCriterion("enterprise_name is not null");
            return (Criteria) this;
        }

        public Criteria andEnterpriseNameEqualTo(String value) {
            addCriterion("enterprise_name =", value, "enterpriseName");
            return (Criteria) this;
        }

        public Criteria andEnterpriseNameNotEqualTo(String value) {
            addCriterion("enterprise_name <>", value, "enterpriseName");
            return (Criteria) this;
        }

        public Criteria andEnterpriseNameGreaterThan(String value) {
            addCriterion("enterprise_name >", value, "enterpriseName");
            return (Criteria) this;
        }

        public Criteria andEnterpriseNameGreaterThanOrEqualTo(String value) {
            addCriterion("enterprise_name >=", value, "enterpriseName");
            return (Criteria) this;
        }

        public Criteria andEnterpriseNameLessThan(String value) {
            addCriterion("enterprise_name <", value, "enterpriseName");
            return (Criteria) this;
        }

        public Criteria andEnterpriseNameLessThanOrEqualTo(String value) {
            addCriterion("enterprise_name <=", value, "enterpriseName");
            return (Criteria) this;
        }

        public Criteria andEnterpriseNameLike(String value) {
            addCriterion("enterprise_name like", value, "enterpriseName");
            return (Criteria) this;
        }

        public Criteria andEnterpriseNameNotLike(String value) {
            addCriterion("enterprise_name not like", value, "enterpriseName");
            return (Criteria) this;
        }

        public Criteria andEnterpriseNameIn(List<String> values) {
            addCriterion("enterprise_name in", values, "enterpriseName");
            return (Criteria) this;
        }

        public Criteria andEnterpriseNameNotIn(List<String> values) {
            addCriterion("enterprise_name not in", values, "enterpriseName");
            return (Criteria) this;
        }

        public Criteria andEnterpriseNameBetween(String value1, String value2) {
            addCriterion("enterprise_name between", value1, value2, "enterpriseName");
            return (Criteria) this;
        }

        public Criteria andEnterpriseNameNotBetween(String value1, String value2) {
            addCriterion("enterprise_name not between", value1, value2, "enterpriseName");
            return (Criteria) this;
        }

        public Criteria andStationIdIsNull() {
            addCriterion("station_id is null");
            return (Criteria) this;
        }

        public Criteria andStationIdIsNotNull() {
            addCriterion("station_id is not null");
            return (Criteria) this;
        }

        public Criteria andStationIdEqualTo(Integer value) {
            addCriterion("station_id =", value, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdNotEqualTo(Integer value) {
            addCriterion("station_id <>", value, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdGreaterThan(Integer value) {
            addCriterion("station_id >", value, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("station_id >=", value, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdLessThan(Integer value) {
            addCriterion("station_id <", value, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdLessThanOrEqualTo(Integer value) {
            addCriterion("station_id <=", value, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdIn(List<Integer> values) {
            addCriterion("station_id in", values, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdNotIn(List<Integer> values) {
            addCriterion("station_id not in", values, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdBetween(Integer value1, Integer value2) {
            addCriterion("station_id between", value1, value2, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationIdNotBetween(Integer value1, Integer value2) {
            addCriterion("station_id not between", value1, value2, "stationId");
            return (Criteria) this;
        }

        public Criteria andStationNameIsNull() {
            addCriterion("station_name is null");
            return (Criteria) this;
        }

        public Criteria andStationNameIsNotNull() {
            addCriterion("station_name is not null");
            return (Criteria) this;
        }

        public Criteria andStationNameEqualTo(String value) {
            addCriterion("station_name =", value, "stationName");
            return (Criteria) this;
        }

        public Criteria andStationNameNotEqualTo(String value) {
            addCriterion("station_name <>", value, "stationName");
            return (Criteria) this;
        }

        public Criteria andStationNameGreaterThan(String value) {
            addCriterion("station_name >", value, "stationName");
            return (Criteria) this;
        }

        public Criteria andStationNameGreaterThanOrEqualTo(String value) {
            addCriterion("station_name >=", value, "stationName");
            return (Criteria) this;
        }

        public Criteria andStationNameLessThan(String value) {
            addCriterion("station_name <", value, "stationName");
            return (Criteria) this;
        }

        public Criteria andStationNameLessThanOrEqualTo(String value) {
            addCriterion("station_name <=", value, "stationName");
            return (Criteria) this;
        }

        public Criteria andStationNameLike(String value) {
            addCriterion("station_name like", value, "stationName");
            return (Criteria) this;
        }

        public Criteria andStationNameNotLike(String value) {
            addCriterion("station_name not like", value, "stationName");
            return (Criteria) this;
        }

        public Criteria andStationNameIn(List<String> values) {
            addCriterion("station_name in", values, "stationName");
            return (Criteria) this;
        }

        public Criteria andStationNameNotIn(List<String> values) {
            addCriterion("station_name not in", values, "stationName");
            return (Criteria) this;
        }

        public Criteria andStationNameBetween(String value1, String value2) {
            addCriterion("station_name between", value1, value2, "stationName");
            return (Criteria) this;
        }

        public Criteria andStationNameNotBetween(String value1, String value2) {
            addCriterion("station_name not between", value1, value2, "stationName");
            return (Criteria) this;
        }

        public Criteria andGasIntegralIsNull() {
            addCriterion("gas_integral is null");
            return (Criteria) this;
        }

        public Criteria andGasIntegralIsNotNull() {
            addCriterion("gas_integral is not null");
            return (Criteria) this;
        }

        public Criteria andGasIntegralEqualTo(Integer value) {
            addCriterion("gas_integral =", value, "gasIntegral");
            return (Criteria) this;
        }

        public Criteria andGasIntegralNotEqualTo(Integer value) {
            addCriterion("gas_integral <>", value, "gasIntegral");
            return (Criteria) this;
        }

        public Criteria andGasIntegralGreaterThan(Integer value) {
            addCriterion("gas_integral >", value, "gasIntegral");
            return (Criteria) this;
        }

        public Criteria andGasIntegralGreaterThanOrEqualTo(Integer value) {
            addCriterion("gas_integral >=", value, "gasIntegral");
            return (Criteria) this;
        }

        public Criteria andGasIntegralLessThan(Integer value) {
            addCriterion("gas_integral <", value, "gasIntegral");
            return (Criteria) this;
        }

        public Criteria andGasIntegralLessThanOrEqualTo(Integer value) {
            addCriterion("gas_integral <=", value, "gasIntegral");
            return (Criteria) this;
        }

        public Criteria andGasIntegralIn(List<Integer> values) {
            addCriterion("gas_integral in", values, "gasIntegral");
            return (Criteria) this;
        }

        public Criteria andGasIntegralNotIn(List<Integer> values) {
            addCriterion("gas_integral not in", values, "gasIntegral");
            return (Criteria) this;
        }

        public Criteria andGasIntegralBetween(Integer value1, Integer value2) {
            addCriterion("gas_integral between", value1, value2, "gasIntegral");
            return (Criteria) this;
        }

        public Criteria andGasIntegralNotBetween(Integer value1, Integer value2) {
            addCriterion("gas_integral not between", value1, value2, "gasIntegral");
            return (Criteria) this;
        }

        public Criteria andGasDiscountIsNull() {
            addCriterion("gas_discount is null");
            return (Criteria) this;
        }

        public Criteria andGasDiscountIsNotNull() {
            addCriterion("gas_discount is not null");
            return (Criteria) this;
        }

        public Criteria andGasDiscountEqualTo(Double value) {
            addCriterion("gas_discount =", value, "gasDiscount");
            return (Criteria) this;
        }

        public Criteria andGasDiscountNotEqualTo(Double value) {
            addCriterion("gas_discount <>", value, "gasDiscount");
            return (Criteria) this;
        }

        public Criteria andGasDiscountGreaterThan(Double value) {
            addCriterion("gas_discount >", value, "gasDiscount");
            return (Criteria) this;
        }

        public Criteria andGasDiscountGreaterThanOrEqualTo(Double value) {
            addCriterion("gas_discount >=", value, "gasDiscount");
            return (Criteria) this;
        }

        public Criteria andGasDiscountLessThan(Double value) {
            addCriterion("gas_discount <", value, "gasDiscount");
            return (Criteria) this;
        }

        public Criteria andGasDiscountLessThanOrEqualTo(Double value) {
            addCriterion("gas_discount <=", value, "gasDiscount");
            return (Criteria) this;
        }

        public Criteria andGasDiscountIn(List<Double> values) {
            addCriterion("gas_discount in", values, "gasDiscount");
            return (Criteria) this;
        }

        public Criteria andGasDiscountNotIn(List<Double> values) {
            addCriterion("gas_discount not in", values, "gasDiscount");
            return (Criteria) this;
        }

        public Criteria andGasDiscountBetween(Double value1, Double value2) {
            addCriterion("gas_discount between", value1, value2, "gasDiscount");
            return (Criteria) this;
        }

        public Criteria andGasDiscountNotBetween(Double value1, Double value2) {
            addCriterion("gas_discount not between", value1, value2, "gasDiscount");
            return (Criteria) this;
        }

        public Criteria andDieselIntegralIsNull() {
            addCriterion("diesel_integral is null");
            return (Criteria) this;
        }

        public Criteria andDieselIntegralIsNotNull() {
            addCriterion("diesel_integral is not null");
            return (Criteria) this;
        }

        public Criteria andDieselIntegralEqualTo(Integer value) {
            addCriterion("diesel_integral =", value, "dieselIntegral");
            return (Criteria) this;
        }

        public Criteria andDieselIntegralNotEqualTo(Integer value) {
            addCriterion("diesel_integral <>", value, "dieselIntegral");
            return (Criteria) this;
        }

        public Criteria andDieselIntegralGreaterThan(Integer value) {
            addCriterion("diesel_integral >", value, "dieselIntegral");
            return (Criteria) this;
        }

        public Criteria andDieselIntegralGreaterThanOrEqualTo(Integer value) {
            addCriterion("diesel_integral >=", value, "dieselIntegral");
            return (Criteria) this;
        }

        public Criteria andDieselIntegralLessThan(Integer value) {
            addCriterion("diesel_integral <", value, "dieselIntegral");
            return (Criteria) this;
        }

        public Criteria andDieselIntegralLessThanOrEqualTo(Integer value) {
            addCriterion("diesel_integral <=", value, "dieselIntegral");
            return (Criteria) this;
        }

        public Criteria andDieselIntegralIn(List<Integer> values) {
            addCriterion("diesel_integral in", values, "dieselIntegral");
            return (Criteria) this;
        }

        public Criteria andDieselIntegralNotIn(List<Integer> values) {
            addCriterion("diesel_integral not in", values, "dieselIntegral");
            return (Criteria) this;
        }

        public Criteria andDieselIntegralBetween(Integer value1, Integer value2) {
            addCriterion("diesel_integral between", value1, value2, "dieselIntegral");
            return (Criteria) this;
        }

        public Criteria andDieselIntegralNotBetween(Integer value1, Integer value2) {
            addCriterion("diesel_integral not between", value1, value2, "dieselIntegral");
            return (Criteria) this;
        }

        public Criteria andDieselDiscountIsNull() {
            addCriterion("diesel_discount is null");
            return (Criteria) this;
        }

        public Criteria andDieselDiscountIsNotNull() {
            addCriterion("diesel_discount is not null");
            return (Criteria) this;
        }

        public Criteria andDieselDiscountEqualTo(Double value) {
            addCriterion("diesel_discount =", value, "dieselDiscount");
            return (Criteria) this;
        }

        public Criteria andDieselDiscountNotEqualTo(Double value) {
            addCriterion("diesel_discount <>", value, "dieselDiscount");
            return (Criteria) this;
        }

        public Criteria andDieselDiscountGreaterThan(Double value) {
            addCriterion("diesel_discount >", value, "dieselDiscount");
            return (Criteria) this;
        }

        public Criteria andDieselDiscountGreaterThanOrEqualTo(Double value) {
            addCriterion("diesel_discount >=", value, "dieselDiscount");
            return (Criteria) this;
        }

        public Criteria andDieselDiscountLessThan(Double value) {
            addCriterion("diesel_discount <", value, "dieselDiscount");
            return (Criteria) this;
        }

        public Criteria andDieselDiscountLessThanOrEqualTo(Double value) {
            addCriterion("diesel_discount <=", value, "dieselDiscount");
            return (Criteria) this;
        }

        public Criteria andDieselDiscountIn(List<Double> values) {
            addCriterion("diesel_discount in", values, "dieselDiscount");
            return (Criteria) this;
        }

        public Criteria andDieselDiscountNotIn(List<Double> values) {
            addCriterion("diesel_discount not in", values, "dieselDiscount");
            return (Criteria) this;
        }

        public Criteria andDieselDiscountBetween(Double value1, Double value2) {
            addCriterion("diesel_discount between", value1, value2, "dieselDiscount");
            return (Criteria) this;
        }

        public Criteria andDieselDiscountNotBetween(Double value1, Double value2) {
            addCriterion("diesel_discount not between", value1, value2, "dieselDiscount");
            return (Criteria) this;
        }

        public Criteria andRechargeIntegralIsNull() {
            addCriterion("recharge_integral is null");
            return (Criteria) this;
        }

        public Criteria andRechargeIntegralIsNotNull() {
            addCriterion("recharge_integral is not null");
            return (Criteria) this;
        }

        public Criteria andRechargeIntegralEqualTo(Integer value) {
            addCriterion("recharge_integral =", value, "rechargeIntegral");
            return (Criteria) this;
        }

        public Criteria andRechargeIntegralNotEqualTo(Integer value) {
            addCriterion("recharge_integral <>", value, "rechargeIntegral");
            return (Criteria) this;
        }

        public Criteria andRechargeIntegralGreaterThan(Integer value) {
            addCriterion("recharge_integral >", value, "rechargeIntegral");
            return (Criteria) this;
        }

        public Criteria andRechargeIntegralGreaterThanOrEqualTo(Integer value) {
            addCriterion("recharge_integral >=", value, "rechargeIntegral");
            return (Criteria) this;
        }

        public Criteria andRechargeIntegralLessThan(Integer value) {
            addCriterion("recharge_integral <", value, "rechargeIntegral");
            return (Criteria) this;
        }

        public Criteria andRechargeIntegralLessThanOrEqualTo(Integer value) {
            addCriterion("recharge_integral <=", value, "rechargeIntegral");
            return (Criteria) this;
        }

        public Criteria andRechargeIntegralIn(List<Integer> values) {
            addCriterion("recharge_integral in", values, "rechargeIntegral");
            return (Criteria) this;
        }

        public Criteria andRechargeIntegralNotIn(List<Integer> values) {
            addCriterion("recharge_integral not in", values, "rechargeIntegral");
            return (Criteria) this;
        }

        public Criteria andRechargeIntegralBetween(Integer value1, Integer value2) {
            addCriterion("recharge_integral between", value1, value2, "rechargeIntegral");
            return (Criteria) this;
        }

        public Criteria andRechargeIntegralNotBetween(Integer value1, Integer value2) {
            addCriterion("recharge_integral not between", value1, value2, "rechargeIntegral");
            return (Criteria) this;
        }

        public Criteria andGradeTypeIsNull() {
            addCriterion("grade_type is null");
            return (Criteria) this;
        }

        public Criteria andGradeTypeIsNotNull() {
            addCriterion("grade_type is not null");
            return (Criteria) this;
        }

        public Criteria andGradeTypeEqualTo(Byte value) {
            addCriterion("grade_type =", value, "gradeType");
            return (Criteria) this;
        }

        public Criteria andGradeTypeNotEqualTo(Byte value) {
            addCriterion("grade_type <>", value, "gradeType");
            return (Criteria) this;
        }

        public Criteria andGradeTypeGreaterThan(Byte value) {
            addCriterion("grade_type >", value, "gradeType");
            return (Criteria) this;
        }

        public Criteria andGradeTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("grade_type >=", value, "gradeType");
            return (Criteria) this;
        }

        public Criteria andGradeTypeLessThan(Byte value) {
            addCriterion("grade_type <", value, "gradeType");
            return (Criteria) this;
        }

        public Criteria andGradeTypeLessThanOrEqualTo(Byte value) {
            addCriterion("grade_type <=", value, "gradeType");
            return (Criteria) this;
        }

        public Criteria andGradeTypeIn(List<Byte> values) {
            addCriterion("grade_type in", values, "gradeType");
            return (Criteria) this;
        }

        public Criteria andGradeTypeNotIn(List<Byte> values) {
            addCriterion("grade_type not in", values, "gradeType");
            return (Criteria) this;
        }

        public Criteria andGradeTypeBetween(Byte value1, Byte value2) {
            addCriterion("grade_type between", value1, value2, "gradeType");
            return (Criteria) this;
        }

        public Criteria andGradeTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("grade_type not between", value1, value2, "gradeType");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Byte value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Byte value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Byte value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Byte value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Byte value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Byte> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Byte> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Byte value1, Byte value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreatedIdIsNull() {
            addCriterion("created_id is null");
            return (Criteria) this;
        }

        public Criteria andCreatedIdIsNotNull() {
            addCriterion("created_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedIdEqualTo(Integer value) {
            addCriterion("created_id =", value, "createdId");
            return (Criteria) this;
        }

        public Criteria andCreatedIdNotEqualTo(Integer value) {
            addCriterion("created_id <>", value, "createdId");
            return (Criteria) this;
        }

        public Criteria andCreatedIdGreaterThan(Integer value) {
            addCriterion("created_id >", value, "createdId");
            return (Criteria) this;
        }

        public Criteria andCreatedIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("created_id >=", value, "createdId");
            return (Criteria) this;
        }

        public Criteria andCreatedIdLessThan(Integer value) {
            addCriterion("created_id <", value, "createdId");
            return (Criteria) this;
        }

        public Criteria andCreatedIdLessThanOrEqualTo(Integer value) {
            addCriterion("created_id <=", value, "createdId");
            return (Criteria) this;
        }

        public Criteria andCreatedIdIn(List<Integer> values) {
            addCriterion("created_id in", values, "createdId");
            return (Criteria) this;
        }

        public Criteria andCreatedIdNotIn(List<Integer> values) {
            addCriterion("created_id not in", values, "createdId");
            return (Criteria) this;
        }

        public Criteria andCreatedIdBetween(Integer value1, Integer value2) {
            addCriterion("created_id between", value1, value2, "createdId");
            return (Criteria) this;
        }

        public Criteria andCreatedIdNotBetween(Integer value1, Integer value2) {
            addCriterion("created_id not between", value1, value2, "createdId");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNull() {
            addCriterion("created_time is null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNotNull() {
            addCriterion("created_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeEqualTo(Date value) {
            addCriterion("created_time =", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotEqualTo(Date value) {
            addCriterion("created_time <>", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThan(Date value) {
            addCriterion("created_time >", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("created_time >=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThan(Date value) {
            addCriterion("created_time <", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThanOrEqualTo(Date value) {
            addCriterion("created_time <=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIn(List<Date> values) {
            addCriterion("created_time in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotIn(List<Date> values) {
            addCriterion("created_time not in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeBetween(Date value1, Date value2) {
            addCriterion("created_time between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotBetween(Date value1, Date value2) {
            addCriterion("created_time not between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedNameIsNull() {
            addCriterion("created_name is null");
            return (Criteria) this;
        }

        public Criteria andCreatedNameIsNotNull() {
            addCriterion("created_name is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedNameEqualTo(String value) {
            addCriterion("created_name =", value, "createdName");
            return (Criteria) this;
        }

        public Criteria andCreatedNameNotEqualTo(String value) {
            addCriterion("created_name <>", value, "createdName");
            return (Criteria) this;
        }

        public Criteria andCreatedNameGreaterThan(String value) {
            addCriterion("created_name >", value, "createdName");
            return (Criteria) this;
        }

        public Criteria andCreatedNameGreaterThanOrEqualTo(String value) {
            addCriterion("created_name >=", value, "createdName");
            return (Criteria) this;
        }

        public Criteria andCreatedNameLessThan(String value) {
            addCriterion("created_name <", value, "createdName");
            return (Criteria) this;
        }

        public Criteria andCreatedNameLessThanOrEqualTo(String value) {
            addCriterion("created_name <=", value, "createdName");
            return (Criteria) this;
        }

        public Criteria andCreatedNameLike(String value) {
            addCriterion("created_name like", value, "createdName");
            return (Criteria) this;
        }

        public Criteria andCreatedNameNotLike(String value) {
            addCriterion("created_name not like", value, "createdName");
            return (Criteria) this;
        }

        public Criteria andCreatedNameIn(List<String> values) {
            addCriterion("created_name in", values, "createdName");
            return (Criteria) this;
        }

        public Criteria andCreatedNameNotIn(List<String> values) {
            addCriterion("created_name not in", values, "createdName");
            return (Criteria) this;
        }

        public Criteria andCreatedNameBetween(String value1, String value2) {
            addCriterion("created_name between", value1, value2, "createdName");
            return (Criteria) this;
        }

        public Criteria andCreatedNameNotBetween(String value1, String value2) {
            addCriterion("created_name not between", value1, value2, "createdName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table enterprise_grade_config
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table enterprise_grade_config
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}