package com.tuyou.tuyoucrm.vo;

import java.io.Serializable;
import java.util.Date;

public class LkStationAdmin implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lk_station_admin.station_admin_id
     *
     * @mbg.generated
     */
    private Integer stationAdminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lk_station_admin.admin_id
     *
     * @mbg.generated
     */
    private String adminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lk_station_admin.enterprise_id
     *
     * @mbg.generated
     */
    private Integer enterpriseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lk_station_admin.enterprise_name
     *
     * @mbg.generated
     */
    private String enterpriseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lk_station_admin.station_id
     *
     * @mbg.generated
     */
    private Integer stationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lk_station_admin.station_name
     *
     * @mbg.generated
     */
    private String stationName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lk_station_admin.created_id
     *
     * @mbg.generated
     */
    private Integer createdId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lk_station_admin.created_name
     *
     * @mbg.generated
     */
    private String createdName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lk_station_admin.created_time
     *
     * @mbg.generated
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lk_station_admin
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lk_station_admin.station_admin_id
     *
     * @return the value of lk_station_admin.station_admin_id
     *
     * @mbg.generated
     */
    public Integer getStationAdminId() {
        return stationAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lk_station_admin.station_admin_id
     *
     * @param stationAdminId the value for lk_station_admin.station_admin_id
     *
     * @mbg.generated
     */
    public void setStationAdminId(Integer stationAdminId) {
        this.stationAdminId = stationAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lk_station_admin.admin_id
     *
     * @return the value of lk_station_admin.admin_id
     *
     * @mbg.generated
     */
    public String getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lk_station_admin.admin_id
     *
     * @param adminId the value for lk_station_admin.admin_id
     *
     * @mbg.generated
     */
    public void setAdminId(String adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lk_station_admin.enterprise_id
     *
     * @return the value of lk_station_admin.enterprise_id
     *
     * @mbg.generated
     */
    public Integer getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lk_station_admin.enterprise_id
     *
     * @param enterpriseId the value for lk_station_admin.enterprise_id
     *
     * @mbg.generated
     */
    public void setEnterpriseId(Integer enterpriseId) {
        this.enterpriseId = enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lk_station_admin.enterprise_name
     *
     * @return the value of lk_station_admin.enterprise_name
     *
     * @mbg.generated
     */
    public String getEnterpriseName() {
        return enterpriseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lk_station_admin.enterprise_name
     *
     * @param enterpriseName the value for lk_station_admin.enterprise_name
     *
     * @mbg.generated
     */
    public void setEnterpriseName(String enterpriseName) {
        this.enterpriseName = enterpriseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lk_station_admin.station_id
     *
     * @return the value of lk_station_admin.station_id
     *
     * @mbg.generated
     */
    public Integer getStationId() {
        return stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lk_station_admin.station_id
     *
     * @param stationId the value for lk_station_admin.station_id
     *
     * @mbg.generated
     */
    public void setStationId(Integer stationId) {
        this.stationId = stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lk_station_admin.station_name
     *
     * @return the value of lk_station_admin.station_name
     *
     * @mbg.generated
     */
    public String getStationName() {
        return stationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lk_station_admin.station_name
     *
     * @param stationName the value for lk_station_admin.station_name
     *
     * @mbg.generated
     */
    public void setStationName(String stationName) {
        this.stationName = stationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lk_station_admin.created_id
     *
     * @return the value of lk_station_admin.created_id
     *
     * @mbg.generated
     */
    public Integer getCreatedId() {
        return createdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lk_station_admin.created_id
     *
     * @param createdId the value for lk_station_admin.created_id
     *
     * @mbg.generated
     */
    public void setCreatedId(Integer createdId) {
        this.createdId = createdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lk_station_admin.created_name
     *
     * @return the value of lk_station_admin.created_name
     *
     * @mbg.generated
     */
    public String getCreatedName() {
        return createdName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lk_station_admin.created_name
     *
     * @param createdName the value for lk_station_admin.created_name
     *
     * @mbg.generated
     */
    public void setCreatedName(String createdName) {
        this.createdName = createdName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lk_station_admin.created_time
     *
     * @return the value of lk_station_admin.created_time
     *
     * @mbg.generated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lk_station_admin.created_time
     *
     * @param createdTime the value for lk_station_admin.created_time
     *
     * @mbg.generated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_station_admin
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", stationAdminId=").append(stationAdminId);
        sb.append(", adminId=").append(adminId);
        sb.append(", enterpriseId=").append(enterpriseId);
        sb.append(", enterpriseName=").append(enterpriseName);
        sb.append(", stationId=").append(stationId);
        sb.append(", stationName=").append(stationName);
        sb.append(", createdId=").append(createdId);
        sb.append(", createdName=").append(createdName);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}