package com.tuyou.tuyoucrm.vo;

import java.io.Serializable;
import java.util.Date;

public class LkUserStationAuth implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lk_user_station_auth.user_oil_id
     *
     * @mbg.generated
     */
    private Integer userOilId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lk_user_station_auth.product_id
     *
     * @mbg.generated
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lk_user_station_auth.station_user_id
     *
     * @mbg.generated
     */
    private Integer stationUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lk_user_station_auth.auth_type
     *
     * @mbg.generated
     */
    private Byte authType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lk_user_station_auth.created_id
     *
     * @mbg.generated
     */
    private Integer createdId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lk_user_station_auth.created_name
     *
     * @mbg.generated
     */
    private String createdName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lk_user_station_auth.created_time
     *
     * @mbg.generated
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lk_user_station_auth
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lk_user_station_auth.user_oil_id
     *
     * @return the value of lk_user_station_auth.user_oil_id
     *
     * @mbg.generated
     */
    public Integer getUserOilId() {
        return userOilId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lk_user_station_auth.user_oil_id
     *
     * @param userOilId the value for lk_user_station_auth.user_oil_id
     *
     * @mbg.generated
     */
    public void setUserOilId(Integer userOilId) {
        this.userOilId = userOilId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lk_user_station_auth.product_id
     *
     * @return the value of lk_user_station_auth.product_id
     *
     * @mbg.generated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lk_user_station_auth.product_id
     *
     * @param productId the value for lk_user_station_auth.product_id
     *
     * @mbg.generated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lk_user_station_auth.station_user_id
     *
     * @return the value of lk_user_station_auth.station_user_id
     *
     * @mbg.generated
     */
    public Integer getStationUserId() {
        return stationUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lk_user_station_auth.station_user_id
     *
     * @param stationUserId the value for lk_user_station_auth.station_user_id
     *
     * @mbg.generated
     */
    public void setStationUserId(Integer stationUserId) {
        this.stationUserId = stationUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lk_user_station_auth.auth_type
     *
     * @return the value of lk_user_station_auth.auth_type
     *
     * @mbg.generated
     */
    public Byte getAuthType() {
        return authType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lk_user_station_auth.auth_type
     *
     * @param authType the value for lk_user_station_auth.auth_type
     *
     * @mbg.generated
     */
    public void setAuthType(Byte authType) {
        this.authType = authType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lk_user_station_auth.created_id
     *
     * @return the value of lk_user_station_auth.created_id
     *
     * @mbg.generated
     */
    public Integer getCreatedId() {
        return createdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lk_user_station_auth.created_id
     *
     * @param createdId the value for lk_user_station_auth.created_id
     *
     * @mbg.generated
     */
    public void setCreatedId(Integer createdId) {
        this.createdId = createdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lk_user_station_auth.created_name
     *
     * @return the value of lk_user_station_auth.created_name
     *
     * @mbg.generated
     */
    public String getCreatedName() {
        return createdName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lk_user_station_auth.created_name
     *
     * @param createdName the value for lk_user_station_auth.created_name
     *
     * @mbg.generated
     */
    public void setCreatedName(String createdName) {
        this.createdName = createdName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lk_user_station_auth.created_time
     *
     * @return the value of lk_user_station_auth.created_time
     *
     * @mbg.generated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lk_user_station_auth.created_time
     *
     * @param createdTime the value for lk_user_station_auth.created_time
     *
     * @mbg.generated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lk_user_station_auth
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userOilId=").append(userOilId);
        sb.append(", productId=").append(productId);
        sb.append(", stationUserId=").append(stationUserId);
        sb.append(", authType=").append(authType);
        sb.append(", createdId=").append(createdId);
        sb.append(", createdName=").append(createdName);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}