package com.tuyou.tuyoucrm.vo;

import java.io.Serializable;

public class RechargeGive implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_give.recharge_give_id
     *
     * @mbg.generated
     */
    private Integer rechargeGiveId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_give.recharge_amount_min
     *
     * @mbg.generated
     */
    private Double rechargeAmountMin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_give.recharge_amount_max
     *
     * @mbg.generated
     */
    private Double rechargeAmountMax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_give.give_percent
     *
     * @mbg.generated
     */
    private Double givePercent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_give.enterprise_id
     *
     * @mbg.generated
     */
    private Integer enterpriseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_give.enterprise_name
     *
     * @mbg.generated
     */
    private String enterpriseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_give.station_id
     *
     * @mbg.generated
     */
    private Integer stationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_give.station_name
     *
     * @mbg.generated
     */
    private String stationName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table recharge_give
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_give.recharge_give_id
     *
     * @return the value of recharge_give.recharge_give_id
     *
     * @mbg.generated
     */
    public Integer getRechargeGiveId() {
        return rechargeGiveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_give.recharge_give_id
     *
     * @param rechargeGiveId the value for recharge_give.recharge_give_id
     *
     * @mbg.generated
     */
    public void setRechargeGiveId(Integer rechargeGiveId) {
        this.rechargeGiveId = rechargeGiveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_give.recharge_amount_min
     *
     * @return the value of recharge_give.recharge_amount_min
     *
     * @mbg.generated
     */
    public Double getRechargeAmountMin() {
        return rechargeAmountMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_give.recharge_amount_min
     *
     * @param rechargeAmountMin the value for recharge_give.recharge_amount_min
     *
     * @mbg.generated
     */
    public void setRechargeAmountMin(Double rechargeAmountMin) {
        this.rechargeAmountMin = rechargeAmountMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_give.recharge_amount_max
     *
     * @return the value of recharge_give.recharge_amount_max
     *
     * @mbg.generated
     */
    public Double getRechargeAmountMax() {
        return rechargeAmountMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_give.recharge_amount_max
     *
     * @param rechargeAmountMax the value for recharge_give.recharge_amount_max
     *
     * @mbg.generated
     */
    public void setRechargeAmountMax(Double rechargeAmountMax) {
        this.rechargeAmountMax = rechargeAmountMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_give.give_percent
     *
     * @return the value of recharge_give.give_percent
     *
     * @mbg.generated
     */
    public Double getGivePercent() {
        return givePercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_give.give_percent
     *
     * @param givePercent the value for recharge_give.give_percent
     *
     * @mbg.generated
     */
    public void setGivePercent(Double givePercent) {
        this.givePercent = givePercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_give.enterprise_id
     *
     * @return the value of recharge_give.enterprise_id
     *
     * @mbg.generated
     */
    public Integer getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_give.enterprise_id
     *
     * @param enterpriseId the value for recharge_give.enterprise_id
     *
     * @mbg.generated
     */
    public void setEnterpriseId(Integer enterpriseId) {
        this.enterpriseId = enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_give.enterprise_name
     *
     * @return the value of recharge_give.enterprise_name
     *
     * @mbg.generated
     */
    public String getEnterpriseName() {
        return enterpriseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_give.enterprise_name
     *
     * @param enterpriseName the value for recharge_give.enterprise_name
     *
     * @mbg.generated
     */
    public void setEnterpriseName(String enterpriseName) {
        this.enterpriseName = enterpriseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_give.station_id
     *
     * @return the value of recharge_give.station_id
     *
     * @mbg.generated
     */
    public Integer getStationId() {
        return stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_give.station_id
     *
     * @param stationId the value for recharge_give.station_id
     *
     * @mbg.generated
     */
    public void setStationId(Integer stationId) {
        this.stationId = stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_give.station_name
     *
     * @return the value of recharge_give.station_name
     *
     * @mbg.generated
     */
    public String getStationName() {
        return stationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_give.station_name
     *
     * @param stationName the value for recharge_give.station_name
     *
     * @mbg.generated
     */
    public void setStationName(String stationName) {
        this.stationName = stationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_give
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", rechargeGiveId=").append(rechargeGiveId);
        sb.append(", rechargeAmountMin=").append(rechargeAmountMin);
        sb.append(", rechargeAmountMax=").append(rechargeAmountMax);
        sb.append(", givePercent=").append(givePercent);
        sb.append(", enterpriseId=").append(enterpriseId);
        sb.append(", enterpriseName=").append(enterpriseName);
        sb.append(", stationId=").append(stationId);
        sb.append(", stationName=").append(stationName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}